// --- DONNÉES FRANÇAISES (data-fr.js) ---

// 1. TEXTES UI (Pour le multilingue)
const TEXTS = {
    title: "MAPTOPIA FR",
    enterBtn: "✨ ENTRER SUR LA CARTE ✨",
    menu: {
        pnj: "PNJs",
        animals: "ANIMAUX",
        bus: "BUS",
        shops: "MAGASINS",
        places: "LIEUX",
        fish: "POISSONS",
        bugs: "INSECTES",
        birds: "OISEAUX",
        resources: "RESSOURCES"
    },
    chat: {
        success: "✅ Message envoyé avec succès !",
        error: "❌ Erreur lors de l'envoi.",
        incomplete: "⚠️ Veuillez remplir tous les champs.",
        wait: "Envoi en cours..."
    },
    quiz: {
        success: "✅ BRAVO !",
        error: "❌ ERREUR !",
        finishTitle: "🏆 EXPERT CONFIRMÉ !",
        finishText: "Vous connaissez Heartopia sur le bout des doigts.",
        quitBtn: "QUITTER LE QUIZ"
    },
    like: {
        thankyou: "MERCI !",
        already: "Vous avez déjà voté !"
    }
};

// 2. LISTE DES PNJS
const PNJ_DATA = [
    [-471, 501, "Bob", "pnj/bob.webp"],
    [-526, 499, "Atara", "pnj/atara.webp"],
    [-478, 493, "Collectionneur", "pnj/collectioneur.webp"],
    [-469, 488, "Dorothée", "pnj/dorothée.webp"],
    [-446, 493, "Massimo", "pnj/massimo.webp"],
    [-412, 418, "Ka Ching", "pnj/ka ching.webp"],
    [-399, 591, "Andrew", "pnj/andrew.webp"],
    [-259, 522, "Eric", "pnj/eric.webp"],
    [-456, 549, "Vanya", "pnj/vanya.webp"],
    [-502, 582, "Naniwa", "pnj/naniwa.webp"],
    [-502, 519, "Mme Joan", "pnj/mme joan.webp"],
    [-807, 419, "Will", "pnj/will.webp"],
    [-355, 809, "Patti", "pnj/patti.webp"],
    [-653, 225, "Vernie", "pnj/vernie.webp"],
    [-498, 526, "Bailey j", "pnj/bayleyj.webp"],
    [-528.3, 560.3, "Blanc", "pnj/blanc.webp"],
    [-499.8, 499.0, "Annie", "pnj/annie.webp"],
    [-532.4, 634.8, "Albert Jr.", "pnj/albert jr.webp"],
    [-734.8, 445.8, "Bill", "pnj/bill.webp"]
];

// 3. BUS
const BUS_DATA = [
    ["Banlieue Ouest",[-533,340]], ["Banlieue Village",[-519,639]], ["Village Pêcheurs",[-654,479]], 
    ["Champ Fleurs",[-532,218]], ["Montagne Thermale",[-222,512]], ["Banlieue Nord",[-373,480]], 
    ["Place Centrale",[-497,481]], ["Forêt",[-500,798]]
];

// 4. MAGASINS
const SHOP_DATA = [
    [-472,487,"Vêtements","vetement.webp"],[-474,503,"Meubles","Meuble.webp"],
    [-496.4,520.6,"Animaux","chien.webp"],[-440,467,"Librairie","Librairie.webp"]
];

// 5. ANIMAUX
const ANIMAL_DATA = [
    {pos: [-691, 783], name: "Panda", img: "panda.webp", radius: 60},
    {pos: [-184, 291], name: "Capybara", img: "capybara.webp", radius: 50},
    {pos: [-533, 340], name: "Lapin", img: "lapin.webp", radius: 40},
    {pos: [-649, 185], name: "Renard", img: "renard.webp", radius: 70},
    {pos: [-737, 512], name: "Loutre", img: "loutre.webp", radius: 40},
    {pos: [-354.3, 277.3], name: "Vison", img: "vison.webp", radius: 10},
    {pos: [-531, 805], name: "Cerf", img: "cerf.webp", radius: 60},
    {pos: [-725, 208], name: "Lama", img: "lama.webp", radius: 50}
];

// 6. LIEUX
const LIEUX_DATA = [
    {pos:[-538,492], name:"Place Centrale", type:"label-ville", startOn:true}, 
    {pos:[-692,506], name:"Village Pêcheurs", type:"label-ville", startOn:true}, 
    {pos:[-438,513], name:"Rue des Habitants", type:"label-ville", startOn:true}, 
    {pos:[-649,185], name:"Champ de Fleurs", type:"label-ville", startOn:true}, 
    {pos:[-440,184], name:"Montagne de la Baleine", type:"label-ville", startOn:true}, 
    {pos:[-184,291], name:"Les Ruines", type:"label-ville", startOn:true}, 
    {pos:[-223,501], name:"Montagne Thermale", type:"label-ville", startOn:true}, 
    {pos:[-228,627], name:"Falaise Rocheuse", type:"label-ville", startOn:true}, 
    {pos:[-531,805], name:"Forêt des Chênes", type:"label-ville", startOn:true}, 
    {pos:[-494,429], name:"Rue des Arts", type:"label-ville", startOn:true}, 
    {pos:[-510,558], name:"Rue des Jardins", type:"label-ville", startOn:true}, 
    {pos:[-736,602], name:"Quai Oriental", type:"label-ville", startOn:true}, 
    {pos:[-690,402], name:"Le Quai", type:"label-ville", startOn:true}, 
    {pos:[-780,387], name:"Phare", type:"label-ville", startOn:true}, 
    {pos:[-691,783], name:"Tremplin", type:"label-ville", startOn:true}, 
    {pos:[-338,933], name:"Île de la Forêt", type:"label-ville", startOn:true}, 
    {pos:[-587,406], name:"Banlieue", type:"label-ville", startOn:true}, 
    {pos:[-725,208], name:"Plage Violette", type:"label-ville", startOn:true}, 
    {pos:[-783,478], name:"Mer Calme", type:"label-eau", startOn:true}, 
    {pos:[-534,92], name:"Mer de la Baleine", type:"label-eau", startOn:true}, 
    {pos:[-68,497], name:"Mer Ancienne", type:"label-eau", startOn:true}, 
    {pos:[-536,232], name:"Lac de la Prairie", type:"label-eau", startOn:true}, 
    {pos:[-337,319], name:"Rivière Aurore", type:"label-eau", startOn:true}, 
    {pos:[-176,394], name:"Lac Volcanique", type:"label-eau", startOn:true}, 
    {pos:[-265,537], name:"Lac de la source Thermale", type:"label-eau", startOn:true}, 
    {pos:[-344,652], name:"Rivière Peu Profonde", type:"label-eau", startOn:true}, 
    {pos:[-598,748], name:"Lac de la Forêt", type:"label-eau", startOn:true}, 
    {pos:[-431,774], name:"Haut Lac Forêt", type:"label-eau", startOn:true}, 
    {pos:[-608,481], name:"Lac de Banlieue", type:"label-eau", startOn:true}, 
    {pos:[-669,368], name:"Rivière Tranquille", type:"label-eau", startOn:true}, 
    {pos:[-674,627], name:"Rivière Arbres Géants", type:"label-eau", startOn:true}, 
    {pos:[-600,600], name:"Champ de Fleurs au Moulin", type:"label-ville", startOn:true}, 
    {pos:[-670,450], name:"Ponton Est", type:"label-ville", startOn:true}
];

// 7. RESSOURCES
const resourcesData = {
    "Framboise": { icon: "resource/framboise.webp", positions: [[-680.8, 330.9], [-668.5, 352.1], [-667.9, 268.5], [-648.3, 288.6], [-613.5, 317.4], [-602.8, 274.5], [-617.6, 211.6], [-571.5, 254.4], [-538.9, 208.6], [-527.8, 251.6], [-535.8, 288.3], [-503.1, 242.9], [-495, 222.4], [-453.8, 222.4], [-438.6, 246], [-395, 247.4], [-387.1, 269.5]] },
    "Myrtille": { icon: "resource/myrtille.webp", positions: [[-642.9, 371.9], [-631.9, 368.4], [-628.5, 365.5], [-606.8, 350.3], [-602.5, 342.3], [-590.1, 334.1], [-575.6, 332.1], [-562.1, 330], [-544.9, 324.5], [-518.4, 320.3], [-515.9, 320.5], [-500.8, 321.1], [-479.3, 328.6], [-468.3, 320], [-437.3, 313.9], [-411.4, 311.4], [-400.3, 311.4], [-379.5, 304.1], [-327.4, 352], [-313.6, 339], [-328.6, 371.5], [-324.4, 389.3], [-297.9, 410.8], [-271.6, 395.4], [-319.9, 413.5], [-330.4, 421.6], [-333.4, 450], [-338.6, 468.6], [-297.4, 484.4], [-349, 489.4], [-356.5, 499.3], [-360.4, 526.4], [-355.5, 545.1], [-352.9, 565.9], [-316, 558.1], [-363.6, 578.4], [-365.3, 609], [-360.9, 628.1], [-343, 634], [-388, 655.4], [-400.9, 654.3], [-421.9, 656.4], [-444.1, 670.6], [-462.5, 654], [-476.8, 654.6], [-491.6, 656.3], [-506.4, 672.4], [-525.4, 688], [-542.6, 650], [-559.3, 644.9], [-575.6, 651], [-597.8, 643.8], [-604.8, 633.8], [-627.9, 619.4]] },
    "Pomme": { icon: "resource/pomme.webp", positions: [[-356.3, 493], [-365.4, 560.1], [-362.4, 581], [-324.6, 570.1], [-296, 610.3], [-365.6, 619.5], [-362.8, 628.5], [-393.5, 654.8], [-420.6, 653.3], [-436.1, 665.4], [-444.4, 685.1], [-436.6, 697.5], [-458.4, 744.9], [-505, 677.3], [-494.5, 657], [-459.8, 653.6], [-530.1, 677.9], [-540.1, 648.6], [-592.8, 676.6], [-606.9, 634.1], [-629.3, 623]] },
    "Grand Arbre": { icon: "resource/grand arbre.webp", positions: [[-612, 424.5], [-641.8, 369], [-351, 329.5], [-414.3, 337.1], [-396.3, 608.9], [-376.3, 624], [-616, 593.6], [-672.3, 642]] },
    "Bois de chêne glissant": { icon: "resource/bois de chaine glissant.webp", positions: [[-532, 787.3]] },
    "Pierre": { icon: "resource/pierre.webp", positions: [[-615.9, 316], [-641.5, 278.8], [-558.4, 257.4], [-535, 292], [-499.5, 241.1], [-466.8, 283.1], [-407.1, 244.1], [-284, 402.8], [-254.6, 367.9], [-309.4, 479.1], [-263, 466.6], [-289.1, 544.6], [-315.5, 567.9], [-298.6, 625.4], [-391.3, 726.9], [-443.6, 697], [-468.6, 733.8], [-519, 714.9], [-564.9, 732.8], [-605.1, 680.3], [-673.9, 684.1]] },
    "Fluorite": { icon: "resource/fluorite.webp", positions: [[-417.8, 313.8]] },
    "Orange": { icon: "resource/orange.webp", positions: [[-650.1, 370.9], [-639.5, 372], [-607.3, 351.4], [-602.9, 343.5], [-588.6, 336.6], [-559.6, 329.5], [-542.1, 324.8], [-515, 319.5], [-470.5, 321], [-461.4, 271.5], [-410.8, 314], [-397.3, 310.1], [-310.9, 339.3], [-327.6, 373.9], [-324.9, 391.9], [-295.4, 411.1], [-330.4, 420.9], [-333.8, 452.9]] }
};

// 8. POISSONS
const fishList = [
    {name:"Ablette", bg:"condition/ablette_lieu.webp", cond:"condition/ablette_meteo.webp", heure:"condition/ablette_heure.webp"},
    {name:"Acantharchus pomotis", bg:"condition/acantharchus_pomotis_lieu.webp", cond:"condition/acantharchus_pomotis_meteo.webp", heure:"condition/acantharchus_pomotis_heure.webp"},
    {name:"Anguille européenne", bg:"condition/anguille_europeenne_lieu.webp", cond:"condition/anguille_europeenne_meteo.webp", heure:"condition/anguille_europeenne_heure.webp"},
    {name:"Aphyosemion striatum", bg:"condition/aphyosemion_striatum_lieu.webp", cond:"condition/aphyosemion_striatum_meteo.webp", heure:"condition/aphyosemion_striatum_heure.webp"},
    {name:"Barbeau", bg:"condition/barbeau_lieu.webp", cond:"condition/barbeau_meteo.webp", heure:"condition/barbeau_heure.webp"},
    {name:"Barbillon", bg:"condition/barbillon_lieu.webp", cond:"condition/barbillon_meteo.webp", heure:"condition/barbillon_heure.webp"},
    {name:"Baudroie", bg:"condition/baudroie_lieu.webp", cond:"condition/baudroie_meteo.webp", heure:"condition/baudroie_heure.webp"},
    {name:"Bernard-l'ermite", bg:"condition/bernard_lhermite_lieu.webp", cond:"condition/bernard_lhermite_meteo.webp", heure:"condition/bernard_lhermite_heure.webp"},
    {name:"Blennie de rivière", bg:"condition/blennie_de_riviere_lieu.webp", cond:"condition/blennie_de_riviere_meteo.webp", heure:"condition/blennie_de_riviere_heure.webp"},
    {name:"Bonite", bg:"condition/bonite_lieu.webp", cond:"condition/bonite_meteo.webp", heure:"condition/bonite_heure.webp"},
    {name:"Brochet tacheté", bg:"condition/brochet_tachete_lieu.webp", cond:"condition/brochet_tachete_meteo.webp", heure:"condition/brochet_tachete_heure.webp"},
    {name:"Carpe argentée", bg:"condition/carpe_argente_lieu.webp", cond:"condition/carpe_argente_meteo.webp", heure:"condition/carpe_argente_heure.webp"},
    {name:"Carpe européenne", bg:"condition/carpe_europeenne_lieu.webp", cond:"condition/carpe_europeenne_meteo.webp", heure:"condition/carpe_europeenne_heure.webp"},
    {name:"Carpe papillon", bg:"condition/carpe_papillon_lieu.webp", cond:"condition/carpe_papillon_meteo.webp", heure:"condition/carpe_papillon_heure.webp"},
    {name:"Carpe noire", bg:"condition/carpe_noire_lieu.webp", cond:"condition/carpe_noire_meteo.webp", heure:"condition/carpe_noire_heure.webp"},
    {name:"Chabot", bg:"condition/chabot_lieu.webp", cond:"condition/chabot_meteo.webp", heure:"condition/chabot_heure.webp"},
    {name:"Chimère argentée", bg:"condition/chimere_argentee_lieu.webp", cond:"condition/chimere_argentee_meteo.webp", heure:"condition/chimere_argentee_heure.webp"},
    {name:"Comète", bg:"condition/comete_coussut_lieu.webp", cond:"condition/comete_coussut_meteo.webp", heure:"condition/comete_coussut_heure.webp"},
    {name:"Crabe de ruisseau", bg:"condition/crabe_de_ruisseau_lieu.webp", cond:"condition/crabe_de_ruisseau_meteo.webp", heure:"condition/crabe_de_ruisseau_heure.webp"},
    {name:"Crevette de la mer", bg:"condition/crevette_de_la_mer_lieu.webp", cond:"condition/crevette_de_la_mer_meteo.webp", heure:"condition/crevette_de_la_mer_heure.webp"},
    {name:"Crevette verte", bg:"condition/crevette_verte_lieu.webp", cond:"condition/crevette_verte_meteo.webp", heure:"condition/crevette_verte_heure.webp"},
    {name:"Écrevisse noble", bg:"condition/ecrevisse_noble_lieu.webp", cond:"condition/ecrevisse_noble_meteo.webp", heure:"condition/ecrevisse_noble_heure.webp"},
    {name:"Écrevisse noble bleue", bg:"condition/ecrevisse_noble_bleue_lieu.webp", cond:"condition/ecrevisse_noble_bleue_meteo.webp", heure:"condition/ecrevisse_noble_bleue_heure.webp"},
    {name:"Églefin", bg:"condition/eglefin_lieu.webp", cond:"condition/eglefin_meteo.webp", heure:"condition/eglefin_heure.webp"},
    {name:"Éperlan", bg:"condition/eperlan_lieu.webp", cond:"condition/eperlan_meteo.webp", heure:"condition/eperlan_heure.webp"},
    {name:"Féra", bg:"condition/fera_lieu.webp", cond:"condition/fera_meteo.webp", heure:"condition/fera_heure.webp"},
    {name:"Grand black-bass", bg:"condition/grand_blackbasse_lieu.webp", cond:"condition/grand_blackbasse_meteo.webp", heure:"condition/grand_blackbasse_heure.webp"},
    {name:"Grenouille européenne", bg:"condition/grenouille_europeenne_lieu.webp", cond:"condition/grenouille_europeenne_meteo.webp", heure:"condition/grenouille_europeenne_heure.webp"},
    {name:"Gobie", bg:"condition/gobie_lieu.webp", cond:"condition/gobie_meteo.webp", heure:"condition/gobie_heure.webp"},
    {name:"Grondin perlon", bg:"condition/grondin_perlon_lieu.webp", cond:"condition/grondin_perlon_meteo.webp", heure:"condition/grondin_perlon_heure.webp"},
    {name:"Hippocampe", bg:"condition/hippocampe_lieu.webp", cond:"condition/hippocampe_meteo.webp", heure:"condition/hippocampe_heure.webp"},
    {name:"Huchon", bg:"condition/huchon_lieu.webp", cond:"condition/huchon_meteo.webp", heure:"condition/huchon_heure.webp"},
    {name:"Langouste européenne", bg:"condition/langouste_europeenne_lieu.webp", cond:"condition/langouste_europeenne_meteo.webp", heure:"condition/langouste_europeenne_heure.webp"},
    {name:"Loche des fleurs", bg:"condition/loche_des_fleurs_lieu.webp", cond:"condition/loche_des_fleurs_meteo.webp", heure:"condition/loche_des_fleurs_heure.webp"},
    {name:"Loche des rochers", bg:"condition/loche_des_rochers_lieu.webp", cond:"condition/loche_des_rochers_meteo.webp", heure:"condition/loche_des_rochers_heure.webp"},
    {name:"Lotte", bg:"condition/lotte_lieu.webp", cond:"condition/lotte_meteo.webp", heure:"condition/lotte_heure.webp"},
    {name:"Maquereau atlantique", bg:"condition/maquereau_atlantique_lieu.webp", cond:"condition/maquereau_atlantique_meteo.webp", heure:"condition/maquereau_atlantique_heure.webp"},
    {name:"Moule", bg:"condition/moule_lieu.webp", cond:"condition/moule_meteo.webp", heure:"condition/moule_heure.webp"},
    {name:"Omble chevalier", bg:"condition/omble_chevalier_lieu.webp", cond:"condition/omble_chevalier_meteo.webp", heure:"condition/omble_chevalier_heure.webp"},
    {name:"Ombrine", bg:"condition/ombrine_lieu.webp", cond:"condition/ombrine_meteo.webp", heure:"condition/ombrine_heure.webp"},
    {name:"Pagellus bogaraveo", bg:"condition/pagellus_bogaraveo_lieu.webp", cond:"condition/pagellus_bogaraveo_meteo.webp", heure:"condition/pagellus_bogaraveo_heure.webp"},
    {name:"Perche de mer", bg:"condition/perche_de_mer_lieu.webp", cond:"condition/perche_de_mer_meteo.webp", heure:"condition/perche_de_mer_heure.webp"},
    {name:"Perche de prunier", bg:"condition/perche_de_prunier_lieu.webp", cond:"condition/perche_de_prunier_meteo.webp", heure:"condition/perche_de_prunier_heure.webp"},
    {name:"Perche de rivière", bg:"condition/perche_de_riviere_lieu.webp", cond:"condition/perche_de_riviere_meteo.webp", heure:"condition/perche_de_riviere_heure.webp"},
    {name:"Pieuvre", bg:"condition/pieuvre_lieu.webp", cond:"condition/pieuvre_meteo.webp", heure:"condition/pieuvre_heure.webp"},
    {name:"Pieuvre naine", bg:"condition/pieuvre_naine_atlantique_lieu.webp", cond:"condition/pieuvre_naine_atlantique_meteo.webp", heure:"condition/pieuvre_naine_atlantique_heure.webp"},
    {name:"Poisson-tigre", bg:"condition/poissontigre_a_ventre_rouge_lieu.webp", cond:"condition/poissontigre_a_ventre_rouge_meteo.webp", heure:"condition/poissontigre_a_ventre_rouge_heure.webp"},
    {name:"Plie européenne", bg:"condition/plie_europeenne_lieu.webp", cond:"condition/plie_europeenne_meteo.webp", heure:"condition/plie_europeenne_heure.webp"},
    {name:"Poisson-clown", bg:"condition/poissonclown_lieu.webp", cond:"condition/poissonclown_meteo.webp", heure:"condition/poissonclown_heure.webp"},
    {name:"Poisson épineux", bg:"condition/poisson_epineux_lieu.webp", cond:"condition/poisson_epineux_meteo.webp", heure:"condition/poisson_epineux_heure.webp"},
    {name:"Poisson-globe de rivière", bg:"condition/poissonglobe_de_riviere_lieu.webp", cond:"condition/poissonglobe_de_riviere_meteo.webp", heure:"condition/poissonglobe_de_riviere_heure.webp"},
    {name:"Poisson rouge", bg:"condition/poisson_rouge_lieu.webp", cond:"condition/poisson_rouge_meteo.webp", heure:"condition/poisson_rouge_heure.webp"},
    {name:"Poisson-ruban", bg:"condition/poisson_ruban_lieu.webp", cond:"condition/poisson_ruban_meteo.webp", heure:"condition/poisson_ruban_heure.webp"},
    {name:"Poisson aux yeux rouges", bg:"condition/poisson_a_yeux_rouges_lieu.webp", cond:"condition/poisson_a_yeux_rouges_meteo.webp", heure:"condition/poisson_a_yeux_rouges_heure.webp"},
    {name:"Régalec", bg:"condition/regalec_lieu.webp", cond:"condition/regalec_meteo.webp", heure:"condition/regalec_heure.webp"},
    {name:"Rouget barbet", bg:"condition/rouget_barbet_lieu.webp", cond:"condition/rouget_barbet_meteo.webp", heure:"condition/rouget_barbet_heure.webp"},
    {name:"Roussette", bg:"condition/roussette_lieu.webp", cond:"condition/roussette_meteo.webp", heure:"condition/roussette_heure.webp"},
    {name:"Sandre blanc", bg:"condition/sandre_blanc_lieu.webp", cond:"condition/sandre_blanc_meteo.webp", heure:"condition/sandre_blanc_heure.webp"},
    {name:"Saumon atlantique", bg:"condition/saumon_atlantique_lieu.webp", cond:"condition/saumon_atlantique_meteo.webp", heure:"condition/saumon_atlantique_heure.webp"},
    {name:"Saumon keta", bg:"condition/saumon_keta_lieu.webp", cond:"condition/saumon_keta_meteo.webp", heure:"condition/saumon_keta_heure.webp"},
    {name:"Saurel", bg:"condition/saurel_lieu.webp", cond:"condition/saurel_meteo.webp", heure:"condition/saurel_heure.webp"},
    {name:"Sardine", bg:"condition/sardine_lieu.webp", cond:"condition/sardine_meteo.webp", heure:"condition/sardine_heure.webp"},
    {name:"Seiche européenne", bg:"condition/seiche_europeenne_lieu.webp", cond:"condition/seiche_europeenne_meteo.webp", heure:"condition/seiche_europeenne_heure.webp"},
    {name:"Silure européen", bg:"condition/silure_europeen_lieu.webp", cond:"condition/silure_europeen_meteo.webp", heure:"condition/silure_europeen_heure.webp"},
    {name:"Tanche dorée", bg:"condition/tanche_doree_lieu.webp", cond:"condition/tanche_doree_meteo.webp", heure:"condition/tanche_doree_heure.webp"},
    {name:"Têtard", bg:"condition/tetard_lieu.webp", cond:"condition/tetard_meteo.webp", heure:"condition/tetard_heure.webp"},
    {name:"Tilapia", bg:"condition/tilapia_lieu.webp", cond:"condition/tilapia_meteo.webp", heure:"condition/tilapia_heure.webp"},
    {name:"Turbot", bg:"condition/turbot_lieu.webp", cond:"condition/turbot_meteo.webp", heure:"condition/turbot_heure.webp"},
    {name:"Vairon", bg:"condition/vairon_lieu.webp", cond:"condition/vairon_meteo.webp", heure:"condition/vairon_heure.webp"},
    {name:"Zingel streber", bg:"condition/zingel_streber_lieu.webp", cond:"condition/zingel_streber_meteo.webp", heure:"condition/zingel_streber_heure.webp"}
];

// 9. INSECTES
const bugList = [
    {name:"Actias neidhoederi", bg:"condition/actias_neidhoederi_lieu.webp", cond:"condition/actias_neidhoederi_meteo.webp", heure:"condition/actias_neidhoederi_heure.webp"},
    {name:"Azuré des nerpruns", bg:"condition/azure_de_porcelaine_lieu.webp", cond:"condition/azure_de_porcelaine_meteo.webp", heure:"condition/azure_de_porcelaine_heure.webp"},
    {name:"Bourdon", bg:"condition/bourdon_lieu.webp", cond:"condition/bourdon_meteo.webp", heure:"condition/bourdon_heure.webp"},
    {name:"Cétoine étoile bleue", bg:"condition/cetoine_etoilee_bleue_lieu.webp", cond:"condition/cetoine_etoilee_bleue_meteo.webp", heure:"condition/cetoine_etoilee_bleue_heure.webp"},
    {name:"Cicindèle verte", bg:"condition/cicindele_verte_lieu.webp", cond:"condition/cicindele_verte_meteo.webp", heure:"condition/cicindele_verte_heure.webp"},
    {name:"Citron aspasia", bg:"condition/citron_aspasia_lieu.webp", cond:"condition/citron_aspasia_meteo.webp", heure:"condition/citron_aspasia_heure.webp"},
    {name:"Coccinelle à 7 points", bg:"condition/coccinelle_a_sept_points_lieu.webp", cond:"condition/coccinelle_a_sept_points_meteo.webp", heure:"condition/coccinelle_a_sept_points_heure.webp"},
    {name:"Coccinelle asiatique", bg:"condition/coccinelle_asiatique_lieu.webp", cond:"condition/coccinelle_asiatique_meteo.webp", heure:"condition/coccinelle_asiatique_heure.webp"},
    {name:"Criocère de l'asperge", bg:"condition/criocere_de_lasperge_lieu.webp", cond:"condition/criocere_de_lasperge_meteo.webp", heure:"condition/criocere_de_lasperge_heure.webp"},
    {name:"Criquet aux pattes massives", bg:"condition/criquet_aux_pattes_massives_lieu.webp", cond:"condition/criquet_aux_pattes_massives_meteo.webp", heure:"condition/criquet_aux_pattes_massives_heure.webp"},
    {name:"Grand agrion", bg:"condition/grand_agrion_lieu.webp", cond:"condition/grand_agrion_meteo.webp", heure:"condition/grand_agrion_heure.webp"},
    {name:"Libellule tachetée", bg:"condition/libellule_tachetee_lieu.webp", cond:"condition/libellule_tachetee_meteo.webp", heure:"condition/libellule_tachetee_heure.webp"},
    {name:"Papillon à anneaux rouges", bg:"condition/papillon_a_anneaux_rouges_lieu.webp", cond:"condition/papillon_a_anneaux_rouges_meteo.webp", heure:"condition/papillon_a_anneaux_rouges_heure.webp"},
    {name:"Papillon à col rouge", bg:"condition/papillon_a_col_rouge_lieu.webp", cond:"condition/papillon_a_col_rouge_meteo.webp", heure:"condition/papillon_a_col_rouge_heure.webp"},
    {name:"Papillon blanc", bg:"condition/papillon_blanc_lieu.webp", cond:"condition/papillon_blanc_meteo.webp", heure:"condition/papillon_blanc_heure.webp"},
    {name:"Papillon doré", bg:"condition/papillon_dore_lieu.webp", cond:"condition/papillon_dore_meteo.webp", heure:"condition/papillon_dore_heure.webp"},
    {name:"Parnassien", bg:"condition/parnassien_lieu.webp", cond:"condition/parnassien_meteo.webp", heure:"condition/parnassien_heure.webp"},
    {name:"Piéride du cresson", bg:"condition/pieride_du_cresson_lieu.webp", cond:"condition/pieride_du_cresson_meteo.webp", heure:"condition/pieride_du_cresson_heure.webp"},
    {name:"Punaise Picasso", bg:"condition/punaise_picasso_lieu.webp", cond:"condition/punaise_picasso_meteo.webp", heure:"condition/punaise_picasso_heure.webp"},
    {name:"Pyrochroa", bg:"condition/pyrochroa_lieu.webp", cond:"condition/pyrochroa_meteo.webp", heure:"condition/pyrochroa_heure.webp"},
    {name:"Pyrrhocore", bg:"condition/pyrrhocoris_apterus_lieu.webp", cond:"condition/pyrrhocoris_apterus_meteo.webp", heure:"condition/pyrrhocoris_apterus_heure.webp"},
    {name:"Sauterelle de l'oasis", bg:"condition/sauterelle_de_loasis_lieu.webp", cond:"condition/sauterelle_de_loasis_meteo.webp", heure:"condition/sauterelle_de_loasis_heure.webp"},
    {name:"Scarabée licorne", bg:"condition/scarabee_unicorne_lieu.webp", cond:"condition/scarabee_unicorne_meteo.webp", heure:"condition/scarabee_unicorne_heure.webp"}
];

// 10. OISEAUX
const birdList = [
    {name:"Ara bleu et jaune", bg:"condition/ara_bleu_et_jaune_lieu.webp", cond:"condition/ara_bleu_et_jaune_meteo.webp", heure:"condition/ara_bleu_et_jaune_heure.webp"},
    {name:"Ara rouge et vert", bg:"condition/ara_rouge_et_vert_lieu.webp", cond:"condition/ara_rouge_et_vert_meteo.webp", heure:"condition/ara_rouge_et_vert_heure.webp"},
    {name:"Ara indigo", bg:"condition/ara_indigo_lieu.webp", cond:"condition/ara_indigo_meteo.webp", heure:"condition/ara_indigo_heure.webp"},
    {name:"Bergeronnette grise", bg:"condition/bergeronnette_grise_lieu.webp", cond:"condition/bergeronnette_grise_meteo.webp", heure:"condition/bergeronnette_grise_heure.webp"},
    {name:"Bouvreuil", bg:"condition/bouvreuil_lieu.webp", cond:"condition/bouvreuil_meteo.webp", heure:"condition/bouvreuil_heure.webp"},
    {name:"Bouvreuil à ventre rouge", bg:"condition/bouvreuil_a_ventre_rouge_lieu.webp", cond:"condition/bouvreuil_a_ventre_rouge_meteo.webp", heure:"condition/bouvreuil_a_ventre_rouge_heure.webp"},
    {name:"Calliste septicolore", bg:"condition/calliste_septicolore_lieu.webp", cond:"condition/calliste_septicolore_meteo.webp", heure:"condition/calliste_septicolore_heure.webp"},
    {name:"Canard à tête blanche", bg:"condition/canard_a_tete_blanche_lieu.webp", cond:"condition/canard_a_tete_blanche_meteo.webp", heure:"condition/canard_a_tete_blanche_heure.webp"},
    {name:"Canard colvert", bg:"condition/canard_colvert_lieu.webp", cond:"condition/canard_colvert_meteo.webp", heure:"condition/canard_colvert_heure.webp"},
    {name:"Canard siffleur", bg:"condition/canard_siffleur_lieu.webp", cond:"condition/canard_siffleur_meteo.webp", heure:"condition/canard_siffleur_heure.webp"},
    {name:"Cardinal à couronne grise", bg:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_lieu.webp", cond:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_meteo.webp", heure:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_heure.webp"},
    {name:"Colombe jambu", bg:"condition/colombe_jambu_lieu.webp", cond:"condition/colombe_jambu_meteo.webp", heure:"condition/colombe_jambu_heure.webp"},
    {name:"Diamant mandarin", bg:"condition/diamant_mandarin_lieu.webp", cond:"condition/diamant_mandarin_meteo.webp", heure:"condition/diamant_mandarin_heure.webp"},
    {name:"Eider royal", bg:"condition/eider_royal_lieu.webp", cond:"condition/eider_royal_meteo.webp", heure:"condition/eider_royal_heure.webp"},
    {name:"Faisan à ventre blanc", bg:"condition/faisan_a_ventre_blanc_lieu.webp", cond:"condition/faisan_a_ventre_blanc_meteo.webp", heure:"condition/faisan_a_ventre_blanc_heure.webp"},
    {name:"Faucon à pattes rouges", bg:"condition/faucon_a_pattes_rouges_lieu.webp", cond:"condition/faucon_a_pattes_rouges_meteo.webp", heure:"condition/faucon_a_pattes_rouges_heure.webp"},
    {name:"Faucon pèlerin", bg:"condition/faucon_pelerin_lieu.webp", cond:"condition/faucon_pelerin_meteo.webp", heure:"condition/faucon_pelerin_heure.webp"},
    {name:"Faucon rouge", bg:"condition/faucon_rouge_lieu.webp", cond:"condition/faucon_rouge_meteo.webp", heure:"condition/faucon_rouge_heure.webp"},
    {name:"Flamant rose américain", bg:"condition/flamant_rose_americain_lieu.webp", cond:"condition/flamant_rose_americain_meteo.webp", heure:"condition/flamant_rose_americain_heure.webp"},
    {name:"Pinson des arbres", bg:"condition/fringilla_coelebs_lieu.webp", cond:"condition/fringilla_coelebs_meteo.webp", heure:"condition/fringilla_coelebs_heure.webp"},
    {name:"Gobemouche vert-de-gris", bg:"condition/gobemouche_vertdegris_lieu.webp", cond:"condition/gobemouche_vertdegris_meteo.webp", heure:"condition/gobemouche_vertdegris_heure.webp"},
    {name:"Goéland", bg:"condition/goeland_lieu.webp", cond:"condition/goeland_meteo.webp", heure:"condition/goeland_heure.webp"},
    {name:"Loriot d'Europe", bg:"condition/golden_oriole_lieu.webp", cond:"condition/golden_oriole_meteo.webp", heure:"condition/golden_oriole_heure.webp"},
    {name:"Grand-duc d'Europe", bg:"condition/grand_duc_deurope_lieu.webp", cond:"condition/grand_duc_deurope_meteo.webp", heure:"condition/grand_duc_deurope_heure.webp"},
    {name:"Grand flamant", bg:"condition/grand_flamant_lieu.webp", cond:"condition/grand_flamant_meteo.webp", heure:"condition/grand_flamant_heure.webp"},
    {name:"Grand pic", bg:"condition/grand_pic_lieu.webp", cond:"condition/grand_pic_meteo.webp", heure:"condition/grand_pic_heure.webp"},
    {name:"Gros-bec", bg:"condition/grosbec_lieu.webp", cond:"condition/grosbec_meteo.webp", heure:"condition/grosbec_heure.webp"},
    {name:"Guêpier d'Europe", bg:"condition/guepier_deurope_lieu.webp", cond:"condition/guepier_deurope_meteo.webp", heure:"condition/guepier_deurope_heure.webp"},
    {name:"Harle piette", bg:"condition/harle_piette_lieu.webp", cond:"condition/harle_piette_meteo.webp", heure:"condition/harle_piette_heure.webp"},
    {name:"Hibou moyen-duc", bg:"condition/hibou_moyen_duc_lieu.webp", cond:"condition/hibou_moyen_duc_meteo.webp", heure:"condition/hibou_moyen_duc_heure.webp"},
    {name:"Jardinier à tête jaune", bg:"condition/jardinier_a_tete_jaune_lieu.webp", cond:"condition/jardinier_a_tete_jaune_meteo.webp", heure:"condition/jardinier_a_tete_jaune_heure.webp"},
    {name:"Linotte à dos blanc", bg:"condition/linotte_a_dos_blanc_lieu.webp", cond:"condition/linotte_a_dos_blanc_meteo.webp", heure:"condition/linotte_a_dos_blanc_heure.webp"},
    {name:"Merle bleu de l'Est", bg:"condition/merle_bleu_de_lest_lieu.webp", cond:"condition/merle_bleu_de_lest_meteo.webp", heure:"condition/merle_bleu_de_lest_heure.webp"},
    {name:"Mésange à menton argent", bg:"condition/mesange_a_menton_argent_lieu.webp", cond:"condition/mesange_a_menton_argent_meteo.webp", heure:"condition/mesange_a_menton_argent_heure.webp"},
    {name:"Mésange bleue", bg:"condition/mesange_bleue_lieu.webp", cond:"condition/mesange_bleue_meteo.webp", heure:"condition/mesange_bleue_heure.webp"},
    {name:"Moucherolle à ventre jaune", bg:"condition/moucherolle_a_ventre_jaune_lieu.webp", cond:"condition/moucherolle_a_ventre_jaune_meteo.webp", heure:"condition/moucherolle_a_ventre_jaune_heure.webp"},
    {name:"Mouette", bg:"condition/mouette_lieu.webp", cond:"condition/mouette_meteo.webp", heure:"condition/mouette_heure.webp"},
    {name:"Panure à moustaches", bg:"condition/panure_a_moustache_lieu.webp", cond:"condition/panure_a_moustache_meteo.webp", heure:"condition/panure_a_moustache_heure.webp"},
    {name:"Paon blanc", bg:"condition/paon_blanc_lieu.webp", cond:"condition/paon_blanc_meteo.webp", heure:"condition/paon_blanc_heure.webp"},
    {name:"Paon bleu", bg:"condition/paon_bleu_lieu.webp", cond:"condition/paon_bleu_meteo.webp", heure:"condition/paon_bleu_heure.webp"},
    {name:"Paon noir", bg:"condition/paon_noir_lieu.webp", cond:"condition/paon_noir_meteo.webp", heure:"condition/paon_noir_heure.webp"},
    {name:"Paon vert", bg:"condition/paon_vert_lieu.webp", cond:"condition/paon_vert_meteo.webp", heure:"condition/paon_vert_heure.webp"},
    {name:"Petit flamant", bg:"condition/petit_flamant_lieu.webp", cond:"condition/petit_flamant_meteo.webp", heure:"condition/petit_flamant_heure.webp"},
    {name:"Pie-grièche à tête rousse", bg:"condition/piegrieche_a_tete_rousse_lieu.webp", cond:"condition/piegrieche_a_tete_rousse_meteo.webp", heure:"condition/piegrieche_a_tete_rousse_heure.webp"},
    {name:"Pigeon aux fruits d'or", bg:"condition/pigeon_aux_fruits_dor_lieu.webp", cond:"condition/pigeon_aux_fruits_dor_meteo.webp", heure:"condition/pigeon_aux_fruits_dor_heure.webp"},
    {name:"Pigeon aux yeux jaunes", bg:"condition/pigeon_aux_yeux_jaunes_lieu.webp", cond:"condition/pigeon_aux_yeux_jaunes_meteo.webp", heure:"condition/pigeon_aux_yeux_jaunes_heure.webp"},
    {name:"Pigeon colombin", bg:"condition/pigeon_colombin_lieu.webp", cond:"condition/pigeon_colombin_meteo.webp", heure:"condition/pigeon_colombin_heure.webp"},
    {name:"Pigeon de Wonga", bg:"condition/pigeon_de_wonga_lieu.webp", cond:"condition/pigeon_de_wonga_meteo.webp", heure:"condition/pigeon_de_wonga_heure.webp"},
    {name:"Pigeon rose", bg:"condition/pigeon_rose_lieu.webp", cond:"condition/pigeon_rose_meteo.webp", heure:"condition/pigeon_rose_heure.webp"},
    {name:"Pinson", bg:"condition/pinson_lieu.webp", cond:"condition/pinson_meteo.webp", heure:"condition/pinson_heure.webp"},
    {name:"Rougegorge", bg:"condition/rougegorge_lieu.webp", cond:"condition/rougegorge_meteo.webp", heure:"condition/rougegorge_heure.webp"},
    {name:"Sittelle", bg:"condition/sittelle_lieu.webp", cond:"condition/sittelle_meteo.webp", heure:"condition/sittelle_heure.webp"},
    {name:"Sterne", bg:"condition/sterne_lieu.webp", cond:"condition/sterne_meteo.webp", heure:"condition/sterne_heure.webp"},
    {name:"Sterne blanche", bg:"condition/sterne_blanche_lieu.webp", cond:"condition/sterne_blanche_meteo.webp", heure:"condition/sterne_blanche_heure.webp"},
    {name:"Tadorne casarca", bg:"condition/tadorne_casarca_lieu.webp", cond:"condition/tadorne_casarca_meteo.webp", heure:"condition/tadorne_casarca_heure.webp"},
    {name:"Tourterelle à tête grise", bg:"condition/tourterelle_a_tete_grise_lieu.webp", cond:"condition/tourterelle_a_tete_grise_meteo.webp", heure:"condition/tourterelle_a_tete_grise_heure.webp"},
    {name:"Tourterelle grise", bg:"condition/tourterelle_grise_lieu.webp", cond:"condition/tourterelle_grise_meteo.webp", heure:"condition/tourterelle_grise_heure.webp"},
    {name:"Tourterelle tigrine", bg:"condition/tourterelle_tigrine_lieu.webp", cond:"condition/tourterelle_tigrine_meteo.webp", heure:"condition/tourterelle_tigrine_heure.webp"},
    {name:"Troglodyte", bg:"condition/troglodyte_lieu.webp", cond:"condition/troglodyte_meteo.webp", heure:"condition/troglodyte_heure.webp"}
];

// 11. QUIZ (Renommé QUIZ_DATA pour être cohérent avec app.js)
const QUIZ_DATA = [
    { q: "Qui est le guide du village ?", o: ["Albert Jr.", "Barnabé", "Eric"], a: 0 },
    { q: "Où trouve-t-on l'Acantharchus pomotis ?", o: ["Mer Calme", "Lac de la Forêt", "Rivière Aurore"], a: 0 },
    { q: "Quel PNJ gère les trouvailles ?", o: ["Le Collectionneur", "Bob", "Massimo"], a: 0 },
    { q: "Quelle météo crée l'arc-en-ciel ?", o: ["Orage", "Brume", "Soleil après pluie"], a: 2 },
    { q: "Où est le Village Pêcheurs ?", o: ["Nord-Est", "Sud-Ouest", "Est"], a: 1 },
    { q: "L'Actias neidhoederi est :", o: ["Matinal", "Diurne", "Nocturne"], a: 2 },
    { q: "Où vit le Capybara ?", o: ["Les Ruines", "Le Plongeoir", "La Plage"], a: 0 },
    { q: "Qui vend les animaux (chiens) ?", o: ["Vernie", "Joan", "Andrew"], a: 1 },
    { q: "Où pêcher le Régalec ?", o: ["Rivières", "Lacs", "Océan"], a: 2 },
    { q: "Où est la zone thermale ?", o: ["Au Nord", "Au Sud", "À l'Ouest"], a: 0 },
    { q: "Le Scarabée licorne vit :", o: ["Quai Oriental", "Champs", "Forêt"], a: 0 },
    { q: "L'Ara indigo est un :", o: ["Poisson", "Insecte", "Oiseau"], a: 2 },
    { q: "La Carpe Papillon vit :", o: ["Eau douce", "Eau salée", "Lac Prairie"], a: 2 },
    { q: "Où se trouve le PNJ Will ?", o: ["Près de la mer", "En montagne", "En forêt"], a: 0 },
    { q: "Couleur du bouton POISSONS ?", o: ["Vert", "Bleu", "Orange"], a: 1 },
    { q: "Le Bourdon vit :", o: ["Lacs", "Champs de fleurs", "Grottes"], a: 1 },
    { q: "La Loutre se trouve :", o: ["Phare", "Village Pêcheurs", "Ruines"], a: 1 },
    { q: "Le Panda vit près de :", o: ["Plongeoir", "Village", "Quai"], a: 0 },
    { q: "L'Éperlan vit :", o: ["Lac Prairie", "Haut Lac", "Océan"], a: 0 },
    { q: "Annie se trouve :", o: ["Place Centrale", "Plage", "Forêt"], a: 0 },
    { q: "Le Lama vit :", o: ["Plage Violette", "Montagne", "Rivière"], a: 0 },
    { q: "Note sur 20 pour la carte ?", o: ["5", "0", "20"], a: 2 },
    { q: "L'Écrevisse bleue vit :", o: ["Lac Forêt", "Océan", "Mer Calme"], a: 0 },
    { q: "La Montagne Baleine est au :", o: ["Sud", "Nord", "Ouest"], a: 2 },
    { q: "Maptopia sert à :", o: ["Vendre des items", "Localiser les ressources", "Remplacer le jeu"], a: 1 },
    { q: "La Bergeronnette est un :", o: ["Oiseau", "Poisson", "Habitant"], a: 1 },
    { q: "Le Cerf vit :", o: ["Plage", "Forêt Chênes", "Ville"], a: 1 },
    { q: "Le Citron aspasia est un :", o: ["Fruit", "Insecte", "Poisson"], a: 1 },
    { q: "Le Quai Oriental est au :", o: ["Nord", "Est", "Sud"], a: 1 },
    { q: "Bob est un :", o: ["Animal", "PNJ", "Lieu"], a: 1 }
];