// --- DATOS EN ESPAÑOL (data-es.js) ---

// 1. TEXTOS DE LA INTERFAZ
const TEXTS = {
    title: "MAPTOPIA ES",
    enterBtn: "✨ ENTRAR AL MAPA ✨",
    menu: {
        pnj: "PNJs",
        animals: "ANIMALES",
        bus: "AUTOBÚS",
        shops: "TIENDAS",
        places: "LUGARES",
        fish: "PECES",
        bugs: "INSECTOS",
        birds: "AVES",
        resources: "RECURSOS"
    },
    chat: {
        success: "✅ ¡Mensaje enviado con éxito!",
        error: "❌ Error al enviar.",
        incomplete: "⚠️ Por favor, rellena todos los campos.",
        wait: "Enviando..."
    },
    quiz: {
        success: "✅ ¡BRAVO!",
        error: "❌ ¡ERROR!",
        finishTitle: "🏆 ¡EXPERTO CONFIRMADO!",
        finishText: "Conoces Heartopia como la palma de tu mano.",
        quitBtn: "SALIR DEL QUIZ"
    },
    like: {
        thankyou: "¡GRACIAS!",
        already: "¡Ya has votado!"
    }
};

// 2. LISTA DE PNJS
const PNJ_DATA = [
    [-471, 501, "Bob", "pnj/bob.webp"],
    [-526, 499, "Atara", "pnj/atara.webp"],
    [-478, 493, "Coleccionista", "pnj/collectioneur.webp"],
    [-469, 488, "Dorothée", "pnj/dorothée.webp"],
    [-446, 493, "Massimo", "pnj/massimo.webp"],
    [-412, 418, "Ka Ching", "pnj/ka ching.webp"],
    [-399, 591, "Andrew", "pnj/andrew.webp"],
    [-259, 522, "Eric", "pnj/eric.webp"],
    [-456, 549, "Vanya", "pnj/vanya.webp"],
    [-502, 582, "Naniwa", "pnj/naniwa.webp"],
    [-502, 519, "Mme Joan", "pnj/mme joan.webp"],
    [-807, 419, "Will", "pnj/will.webp"],
    [-355, 809, "Patti", "pnj/patti.webp"],
    [-653, 225, "Vernie", "pnj/vernie.webp"],
    [-498, 526, "Bailey j", "pnj/bayleyj.webp"],
    [-528.3, 560.3, "Blanc", "pnj/blanc.webp"],
    [-499.8, 499.0, "Annie", "pnj/annie.webp"],
    [-532.4, 634.8, "Albert Jr.", "pnj/albert jr.webp"],
    [-734.8, 445.8, "Bill", "pnj/bill.webp"]
];

// 3. PARADAS DE AUTOBÚS
const BUS_DATA = [
    ["Suburbio Oeste",[-533,340]], ["Suburbio del Pueblo",[-519,639]], ["Pueblo Pescadores",[-654,479]], 
    ["Campo de Flores",[-532,218]], ["Montaña Termal",[-222,512]], ["Suburbio Norte",[-373,480]], 
    ["Plaza Central",[-497,481]], ["Bosque",[-500,798]]
];

// 4. TIENDAS
const SHOP_DATA = [
    [-472,487,"Ropa","vetement.webp"],[-474,503,"Muebles","Meuble.webp"],
    [-496.4,520.6,"Mascotas","chien.webp"],[-440,467,"Librería","Librairie.webp"]
];

// 5. ANIMALES
const ANIMAL_DATA = [
    {pos: [-691, 783], name: "Panda", img: "panda.webp", radius: 60},
    {pos: [-184, 291], name: "Capibara", img: "capybara.webp", radius: 50},
    {pos: [-533, 340], name: "Conejo", img: "lapin.webp", radius: 40},
    {pos: [-649, 185], name: "Zorro", img: "renard.webp", radius: 70},
    {pos: [-737, 512], name: "Nutria", img: "loutre.webp", radius: 40},
    {pos: [-354.3, 277.3], name: "Visón", img: "vison.webp", radius: 10},
    {pos: [-531, 805], name: "Ciervo", img: "cerf.webp", radius: 60},
    {pos: [-725, 208], name: "Llama", img: "lama.webp", radius: 50}
];

// 6. LUGARES
const LIEUX_DATA = [
    {pos:[-538,492], name:"Plaza Central", type:"label-ville", startOn:true}, 
    {pos:[-692,506], name:"Pueblo Pescadores", type:"label-ville", startOn:true}, 
    {pos:[-438,513], name:"Calle de los Habitantes", type:"label-ville", startOn:true}, 
    {pos:[-649,185], name:"Campo de Flores", type:"label-ville", startOn:true}, 
    {pos:[-440,184], name:"Montaña Ballena", type:"label-ville", startOn:true}, 
    {pos:[-184,291], name:"Las Ruinas", type:"label-ville", startOn:true}, 
    {pos:[-223,501], name:"Montaña Termal", type:"label-ville", startOn:true}, 
    {pos:[-228,627], name:"Acantilado Rocoso", type:"label-ville", startOn:true}, 
    {pos:[-531,805], name:"Bosque de Robles", type:"label-ville", startOn:true}, 
    {pos:[-494,429], name:"Calle de las Artes", type:"label-ville", startOn:true}, 
    {pos:[-510,558], name:"Calle de los Jardines", type:"label-ville", startOn:true}, 
    {pos:[-736,602], name:"Muelle Oriental", type:"label-ville", startOn:true}, 
    {pos:[-690,402], name:"El Muelle", type:"label-ville", startOn:true}, 
    {pos:[-780,387], name:"Faro", type:"label-ville", startOn:true}, 
    {pos:[-691,783], name:"Trampolín", type:"label-ville", startOn:true}, 
    {pos:[-338,933], name:"Isla del Bosque", type:"label-ville", startOn:true}, 
    {pos:[-587,406], name:"Suburbios", type:"label-ville", startOn:true}, 
    {pos:[-725,208], name:"Playa Púrpura", type:"label-ville", startOn:true}, 
    {pos:[-783,478], name:"Mar en Calma", type:"label-eau", startOn:true}, 
    {pos:[-534,92], name:"Mar Ballena", type:"label-eau", startOn:true}, 
    {pos:[-68,497], name:"Mar Antiguo", type:"label-eau", startOn:true}, 
    {pos:[-536,232], name:"Lago de la Pradera", type:"label-eau", startOn:true}, 
    {pos:[-337,319], name:"Río Aurora", type:"label-eau", startOn:true}, 
    {pos:[-176,394], name:"Lago Volcánico", type:"label-eau", startOn:true}, 
    {pos:[-265,537], name:"Lago Termal", type:"label-eau", startOn:true}, 
    {pos:[-344,652], name:"Río Poco Profundo", type:"label-eau", startOn:true}, 
    {pos:[-598,748], name:"Lago del Bosque", type:"label-eau", startOn:true}, 
    {pos:[-431,774], name:"Lago Superior", type:"label-eau", startOn:true}, 
    {pos:[-608,481], name:"Lago Suburbano", type:"label-eau", startOn:true}, 
    {pos:[-669,368], name:"Río Tranquilo", type:"label-eau", startOn:true}, 
    {pos:[-674,627], name:"Río Árboles Gigantes", type:"label-eau", startOn:true}, 
    {pos:[-600,600], name:"Molino de Flores", type:"label-ville", startOn:true}, 
    {pos:[-670,450], name:"Pontón Este", type:"label-ville", startOn:true}
];

// 7. RECURSOS
const resourcesData = {
    "Frambuesa": { icon: "resource/framboise.webp", positions: [[-680.8, 330.9], [-668.5, 352.1], [-667.9, 268.5], [-648.3, 288.6], [-613.5, 317.4], [-602.8, 274.5], [-617.6, 211.6], [-571.5, 254.4], [-538.9, 208.6], [-527.8, 251.6], [-535.8, 288.3], [-503.1, 242.9], [-495, 222.4], [-453.8, 222.4], [-438.6, 246], [-395, 247.4], [-387.1, 269.5]] },
    "Arándano": { icon: "resource/myrtille.webp", positions: [[-642.9, 371.9], [-631.9, 368.4], [-628.5, 365.5], [-606.8, 350.3], [-602.5, 342.3], [-590.1, 334.1], [-575.6, 332.1], [-562.1, 330], [-544.9, 324.5], [-518.4, 320.3], [-515.9, 320.5], [-500.8, 321.1], [-479.3, 328.6], [-468.3, 320], [-437.3, 313.9], [-411.4, 311.4], [-400.3, 311.4], [-379.5, 304.1], [-327.4, 352], [-313.6, 339], [-328.6, 371.5], [-324.4, 389.3], [-297.9, 410.8], [-271.6, 395.4], [-319.9, 413.5], [-330.4, 421.6], [-333.4, 450], [-338.6, 468.6], [-297.4, 484.4], [-349, 489.4], [-356.5, 499.3], [-360.4, 526.4], [-355.5, 545.1], [-352.9, 565.9], [-316, 558.1], [-363.6, 578.4], [-365.3, 609], [-360.9, 628.1], [-343, 634], [-388, 655.4], [-400.9, 654.3], [-421.9, 656.4], [-444.1, 670.6], [-462.5, 654], [-476.8, 654.6], [-491.6, 656.3], [-506.4, 672.4], [-525.4, 688], [-542.6, 650], [-559.3, 644.9], [-575.6, 651], [-597.8, 643.8], [-604.8, 633.8], [-627.9, 619.4]] },
    "Manzana": { icon: "resource/pomme.webp", positions: [[-356.3, 493], [-365.4, 560.1], [-362.4, 581], [-324.6, 570.1], [-296, 610.3], [-365.6, 619.5], [-362.8, 628.5], [-393.5, 654.8], [-420.6, 653.3], [-436.1, 665.4], [-444.4, 685.1], [-436.6, 697.5], [-458.4, 744.9], [-505, 677.3], [-494.5, 657], [-459.8, 653.6], [-530.1, 677.9], [-540.1, 648.6], [-592.8, 676.6], [-606.9, 634.1], [-629.3, 623]] },
    "Gran Árbol": { icon: "resource/grand arbre.webp", positions: [[-612, 424.5], [-641.8, 369], [-351, 329.5], [-414.3, 337.1], [-396.3, 608.9], [-376.3, 624], [-616, 593.6], [-672.3, 642]] },
    "Madera de roble resbaladiza": { icon: "resource/bois de chaine glissant.webp", positions: [[-532, 787.3]] },
    "Piedra": { icon: "resource/pierre.webp", positions: [[-615.9, 316], [-641.5, 278.8], [-558.4, 257.4], [-535, 292], [-499.5, 241.1], [-466.8, 283.1], [-407.1, 244.1], [-284, 402.8], [-254.6, 367.9], [-309.4, 479.1], [-263, 466.6], [-289.1, 544.6], [-315.5, 567.9], [-298.6, 625.4], [-391.3, 726.9], [-443.6, 697], [-468.6, 733.8], [-519, 714.9], [-564.9, 732.8], [-605.1, 680.3], [-673.9, 684.1]] },
    "Fluorita": { icon: "resource/fluorite.webp", positions: [[-417.8, 313.8]] },
    "Naranja": { icon: "resource/orange.webp", positions: [[-650.1, 370.9], [-639.5, 372], [-607.3, 351.4], [-602.9, 343.5], [-588.6, 336.6], [-559.6, 329.5], [-542.1, 324.8], [-515, 319.5], [-470.5, 321], [-461.4, 271.5], [-410.8, 314], [-397.3, 310.1], [-310.9, 339.3], [-327.6, 373.9], [-324.9, 391.9], [-295.4, 411.1], [-330.4, 420.9], [-333.8, 452.9]] }
};

// 8. PECES (Traducciones o Nombres Científicos)
const fishList = [
    {name:"Alburno", bg:"condition/ablette_lieu.webp", cond:"condition/ablette_meteo.webp", heure:"condition/ablette_heure.webp"},
    {name:"Acantharchus pomotis", bg:"condition/acantharchus_pomotis_lieu.webp", cond:"condition/acantharchus_pomotis_meteo.webp", heure:"condition/acantharchus_pomotis_heure.webp"},
    {name:"Anguila Europea", bg:"condition/anguille_europeenne_lieu.webp", cond:"condition/anguille_europeenne_meteo.webp", heure:"condition/anguille_europeenne_heure.webp"},
    {name:"Aphyosemion striatum", bg:"condition/aphyosemion_striatum_lieu.webp", cond:"condition/aphyosemion_striatum_meteo.webp", heure:"condition/aphyosemion_striatum_heure.webp"},
    {name:"Barbo", bg:"condition/barbeau_lieu.webp", cond:"condition/barbeau_meteo.webp", heure:"condition/barbeau_heure.webp"},
    {name:"Barbillon", bg:"condition/barbillon_lieu.webp", cond:"condition/barbillon_meteo.webp", heure:"condition/barbillon_heure.webp"},
    {name:"Rape", bg:"condition/baudroie_lieu.webp", cond:"condition/baudroie_meteo.webp", heure:"condition/baudroie_heure.webp"},
    {name:"Cangrejo Ermitaño", bg:"condition/bernard_lhermite_lieu.webp", cond:"condition/bernard_lhermite_meteo.webp", heure:"condition/bernard_lhermite_heure.webp"},
    {name:"Blénido de río", bg:"condition/blennie_de_riviere_lieu.webp", cond:"condition/blennie_de_riviere_meteo.webp", heure:"condition/blennie_de_riviere_heure.webp"},
    {name:"Bonito", bg:"condition/bonite_lieu.webp", cond:"condition/bonite_meteo.webp", heure:"condition/bonite_heure.webp"},
    {name:"Lucio Moteado", bg:"condition/brochet_tachete_lieu.webp", cond:"condition/brochet_tachete_meteo.webp", heure:"condition/brochet_tachete_heure.webp"},
    {name:"Carpa Plateada", bg:"condition/carpe_argente_lieu.webp", cond:"condition/carpe_argente_meteo.webp", heure:"condition/carpe_argente_heure.webp"},
    {name:"Carpa Europea", bg:"condition/carpe_europeenne_lieu.webp", cond:"condition/carpe_europeenne_meteo.webp", heure:"condition/carpe_europeenne_heure.webp"},
    {name:"Carpa Mariposa", bg:"condition/carpe_papillon_lieu.webp", cond:"condition/carpe_papillon_meteo.webp", heure:"condition/carpe_papillon_heure.webp"},
    {name:"Carpa Negra", bg:"condition/carpe_noire_lieu.webp", cond:"condition/carpe_noire_meteo.webp", heure:"condition/carpe_noire_heure.webp"},
    {name:"Coto", bg:"condition/chabot_lieu.webp", cond:"condition/chabot_meteo.webp", heure:"condition/chabot_heure.webp"},
    {name:"Quimera Plateada", bg:"condition/chimere_argentee_lieu.webp", cond:"condition/chimere_argentee_meteo.webp", heure:"condition/chimere_argentee_heure.webp"},
    {name:"Pez Dorado Cometa", bg:"condition/comete_coussut_lieu.webp", cond:"condition/comete_coussut_meteo.webp", heure:"condition/comete_coussut_heure.webp"},
    {name:"Cangrejo de Río", bg:"condition/crabe_de_ruisseau_lieu.webp", cond:"condition/crabe_de_ruisseau_meteo.webp", heure:"condition/crabe_de_ruisseau_heure.webp"},
    {name:"Camarón de Mar", bg:"condition/crevette_de_la_mer_lieu.webp", cond:"condition/crevette_de_la_mer_meteo.webp", heure:"condition/crevette_de_la_mer_heure.webp"},
    {name:"Camarón Verde", bg:"condition/crevette_verte_lieu.webp", cond:"condition/crevette_verte_meteo.webp", heure:"condition/crevette_verte_heure.webp"},
    {name:"Cangrejo Noble", bg:"condition/ecrevisse_noble_lieu.webp", cond:"condition/ecrevisse_noble_meteo.webp", heure:"condition/ecrevisse_noble_heure.webp"},
    {name:"Cangrejo Noble Azul", bg:"condition/ecrevisse_noble_bleue_lieu.webp", cond:"condition/ecrevisse_noble_bleue_meteo.webp", heure:"condition/ecrevisse_noble_bleue_heure.webp"},
    {name:"Eglefino", bg:"condition/eglefin_lieu.webp", cond:"condition/eglefin_meteo.webp", heure:"condition/eglefin_heure.webp"},
    {name:"Eperlano", bg:"condition/eperlan_lieu.webp", cond:"condition/eperlan_meteo.webp", heure:"condition/eperlan_heure.webp"},
    {name:"Pez Blanco", bg:"condition/fera_lieu.webp", cond:"condition/fera_meteo.webp", heure:"condition/fera_heure.webp"},
    {name:"Gran Perca", bg:"condition/grand_blackbasse_lieu.webp", cond:"condition/grand_blackbasse_meteo.webp", heure:"condition/grand_blackbasse_heure.webp"},
    {name:"Rana Europea", bg:"condition/grenouille_europeenne_lieu.webp", cond:"condition/grenouille_europeenne_meteo.webp", heure:"condition/grenouille_europeenne_heure.webp"},
    {name:"Gobio", bg:"condition/gobie_lieu.webp", cond:"condition/gobie_meteo.webp", heure:"condition/gobie_heure.webp"},
    {name:"Rubio", bg:"condition/grondin_perlon_lieu.webp", cond:"condition/grondin_perlon_meteo.webp", heure:"condition/grondin_perlon_heure.webp"},
    {name:"Caballito de Mar", bg:"condition/hippocampe_lieu.webp", cond:"condition/hippocampe_meteo.webp", heure:"condition/hippocampe_heure.webp"},
    {name:"Hucho Hucho", bg:"condition/huchon_lieu.webp", cond:"condition/huchon_meteo.webp", heure:"condition/huchon_heure.webp"},
    {name:"Langosta Europea", bg:"condition/langouste_europeenne_lieu.webp", cond:"condition/langouste_europeenne_meteo.webp", heure:"condition/langouste_europeenne_heure.webp"},
    {name:"Locha de Flores", bg:"condition/loche_des_fleurs_lieu.webp", cond:"condition/loche_des_fleurs_meteo.webp", heure:"condition/loche_des_fleurs_heure.webp"},
    {name:"Locha de Roca", bg:"condition/loche_des_rochers_lieu.webp", cond:"condition/loche_des_rochers_meteo.webp", heure:"condition/loche_des_rochers_heure.webp"},
    {name:"Rape", bg:"condition/lotte_lieu.webp", cond:"condition/lotte_meteo.webp", heure:"condition/lotte_heure.webp"},
    {name:"Caballa del Atlántico", bg:"condition/maquereau_atlantique_lieu.webp", cond:"condition/maquereau_atlantique_meteo.webp", heure:"condition/maquereau_atlantique_heure.webp"},
    {name:"Mejillón", bg:"condition/moule_lieu.webp", cond:"condition/moule_meteo.webp", heure:"condition/moule_heure.webp"},
    {name:"Salvelino", bg:"condition/omble_chevalier_lieu.webp", cond:"condition/omble_chevalier_meteo.webp", heure:"condition/omble_chevalier_heure.webp"},
    {name:"Verrugato", bg:"condition/ombrine_lieu.webp", cond:"condition/ombrine_meteo.webp", heure:"condition/ombrine_heure.webp"},
    {name:"Besugo", bg:"condition/pagellus_bogaraveo_lieu.webp", cond:"condition/pagellus_bogaraveo_meteo.webp", heure:"condition/pagellus_bogaraveo_heure.webp"},
    {name:"Perca de Mar", bg:"condition/perche_de_mer_lieu.webp", cond:"condition/perche_de_mer_meteo.webp", heure:"condition/perche_de_mer_heure.webp"},
    {name:"Perca de Ciruela", bg:"condition/perche_de_prunier_lieu.webp", cond:"condition/perche_de_prunier_meteo.webp", heure:"condition/perche_de_prunier_heure.webp"},
    {name:"Perca de Río", bg:"condition/perche_de_riviere_lieu.webp", cond:"condition/perche_de_riviere_meteo.webp", heure:"condition/perche_de_riviere_heure.webp"},
    {name:"Pulpo", bg:"condition/pieuvre_lieu.webp", cond:"condition/pieuvre_meteo.webp", heure:"condition/pieuvre_heure.webp"},
    {name:"Pulpo Enano", bg:"condition/pieuvre_naine_atlantique_lieu.webp", cond:"condition/pieuvre_naine_atlantique_meteo.webp", heure:"condition/pieuvre_naine_atlantique_heure.webp"},
    {name:"Pez Tigre", bg:"condition/poissontigre_a_ventre_rouge_lieu.webp", cond:"condition/poissontigre_a_ventre_rouge_meteo.webp", heure:"condition/poissontigre_a_ventre_rouge_heure.webp"},
    {name:"Solla Europea", bg:"condition/plie_europeenne_lieu.webp", cond:"condition/plie_europeenne_meteo.webp", heure:"condition/plie_europeenne_heure.webp"},
    {name:"Pez Payaso", bg:"condition/poissonclown_lieu.webp", cond:"condition/poissonclown_meteo.webp", heure:"condition/poissonclown_heure.webp"},
    {name:"Espinoso", bg:"condition/poisson_epineux_lieu.webp", cond:"condition/poisson_epineux_meteo.webp", heure:"condition/poisson_epineux_heure.webp"},
    {name:"Pez Globo de Río", bg:"condition/poissonglobe_de_riviere_lieu.webp", cond:"condition/poissonglobe_de_riviere_meteo.webp", heure:"condition/poissonglobe_de_riviere_heure.webp"},
    {name:"Pez Dorado", bg:"condition/poisson_rouge_lieu.webp", cond:"condition/poisson_rouge_meteo.webp", heure:"condition/poisson_rouge_heure.webp"},
    {name:"Pez Cinta", bg:"condition/poisson_ruban_lieu.webp", cond:"condition/poisson_ruban_meteo.webp", heure:"condition/poisson_ruban_heure.webp"},
    {name:"Pez de Ojos Rojos", bg:"condition/poisson_a_yeux_rouges_lieu.webp", cond:"condition/poisson_a_yeux_rouges_meteo.webp", heure:"condition/poisson_a_yeux_rouges_heure.webp"},
    {name:"Pez Remo", bg:"condition/regalec_lieu.webp", cond:"condition/regalec_meteo.webp", heure:"condition/regalec_heure.webp"},
    {name:"Salmonete", bg:"condition/rouget_barbet_lieu.webp", cond:"condition/rouget_barbet_meteo.webp", heure:"condition/rouget_barbet_heure.webp"},
    {name:"Pintarroja", bg:"condition/roussette_lieu.webp", cond:"condition/roussette_meteo.webp", heure:"condition/roussette_heure.webp"},
    {name:"Lucioperca Blanca", bg:"condition/sandre_blanc_lieu.webp", cond:"condition/sandre_blanc_meteo.webp", heure:"condition/sandre_blanc_heure.webp"},
    {name:"Salmón del Atlántico", bg:"condition/saumon_atlantique_lieu.webp", cond:"condition/saumon_atlantique_meteo.webp", heure:"condition/saumon_atlantique_heure.webp"},
    {name:"Salmón Keta", bg:"condition/saumon_keta_lieu.webp", cond:"condition/saumon_keta_meteo.webp", heure:"condition/saumon_keta_heure.webp"},
    {name:"Jurel", bg:"condition/saurel_lieu.webp", cond:"condition/saurel_meteo.webp", heure:"condition/saurel_heure.webp"},
    {name:"Sardina", bg:"condition/sardine_lieu.webp", cond:"condition/sardine_meteo.webp", heure:"condition/sardine_heure.webp"},
    {name:"Sepia", bg:"condition/seiche_europeenne_lieu.webp", cond:"condition/seiche_europeenne_meteo.webp", heure:"condition/seiche_europeenne_heure.webp"},
    {name:"Siluro", bg:"condition/silure_europeen_lieu.webp", cond:"condition/silure_europeen_meteo.webp", heure:"condition/silure_europeen_heure.webp"},
    {name:"Tenca Dorada", bg:"condition/tanche_doree_lieu.webp", cond:"condition/tanche_doree_meteo.webp", heure:"condition/tanche_doree_heure.webp"},
    {name:"Renacuajo", bg:"condition/tetard_lieu.webp", cond:"condition/tetard_meteo.webp", heure:"condition/tetard_heure.webp"},
    {name:"Tilapia", bg:"condition/tilapia_lieu.webp", cond:"condition/tilapia_meteo.webp", heure:"condition/tilapia_heure.webp"},
    {name:"Rodaballo", bg:"condition/turbot_lieu.webp", cond:"condition/turbot_meteo.webp", heure:"condition/turbot_heure.webp"},
    {name:"Piscardo", bg:"condition/vairon_lieu.webp", cond:"condition/vairon_meteo.webp", heure:"condition/vairon_heure.webp"},
    {name:"Zingel Streber", bg:"condition/zingel_streber_lieu.webp", cond:"condition/zingel_streber_meteo.webp", heure:"condition/zingel_streber_heure.webp"}
];

// 9. INSECTOS
const bugList = [
    {name:"Actias neidhoederi", bg:"condition/actias_neidhoederi_lieu.webp", cond:"condition/actias_neidhoederi_meteo.webp", heure:"condition/actias_neidhoederi_heure.webp"},
    {name:"Celestina", bg:"condition/azure_de_porcelaine_lieu.webp", cond:"condition/azure_de_porcelaine_meteo.webp", heure:"condition/azure_de_porcelaine_heure.webp"},
    {name:"Abejorro", bg:"condition/bourdon_lieu.webp", cond:"condition/bourdon_meteo.webp", heure:"condition/bourdon_heure.webp"},
    {name:"Escarabajo Flor Azul", bg:"condition/cetoine_etoilee_bleue_lieu.webp", cond:"condition/cetoine_etoilee_bleue_meteo.webp", heure:"condition/cetoine_etoilee_bleue_heure.webp"},
    {name:"Escarabajo Tigre Verde", bg:"condition/cicindele_verte_lieu.webp", cond:"condition/cicindele_verte_meteo.webp", heure:"condition/cicindele_verte_heure.webp"},
    {name:"Gonepteryx aspasia", bg:"condition/citron_aspasia_lieu.webp", cond:"condition/citron_aspasia_meteo.webp", heure:"condition/citron_aspasia_heure.webp"},
    {name:"Mariquita de 7 puntos", bg:"condition/coccinelle_a_sept_points_lieu.webp", cond:"condition/coccinelle_a_sept_points_meteo.webp", heure:"condition/coccinelle_a_sept_points_heure.webp"},
    {name:"Mariquita Asiática", bg:"condition/coccinelle_asiatique_lieu.webp", cond:"condition/coccinelle_asiatique_meteo.webp", heure:"condition/coccinelle_asiatique_heure.webp"},
    {name:"Escarabajo del Espárrago", bg:"condition/criocere_de_lasperge_lieu.webp", cond:"condition/criocere_de_lasperge_meteo.webp", heure:"condition/criocere_de_lasperge_heure.webp"},
    {name:"Saltamontes Robusto", bg:"condition/criquet_aux_pattes_massives_lieu.webp", cond:"condition/criquet_aux_pattes_massives_meteo.webp", heure:"condition/criquet_aux_pattes_massives_heure.webp"},
    {name:"Gran Caballito del Diablo", bg:"condition/grand_agrion_lieu.webp", cond:"condition/grand_agrion_meteo.webp", heure:"condition/grand_agrion_heure.webp"},
    {name:"Libélula Moteada", bg:"condition/libellule_tachetee_lieu.webp", cond:"condition/libellule_tachetee_meteo.webp", heure:"condition/libellule_tachetee_heure.webp"},
    {name:"Mariposa Anillos Rojos", bg:"condition/papillon_a_anneaux_rouges_lieu.webp", cond:"condition/papillon_a_anneaux_rouges_meteo.webp", heure:"condition/papillon_a_anneaux_rouges_heure.webp"},
    {name:"Mariposa Cuello Rojo", bg:"condition/papillon_a_col_rouge_lieu.webp", cond:"condition/papillon_a_col_rouge_meteo.webp", heure:"condition/papillon_a_col_rouge_heure.webp"},
    {name:"Mariposa Blanca", bg:"condition/papillon_blanc_lieu.webp", cond:"condition/papillon_blanc_meteo.webp", heure:"condition/papillon_blanc_heure.webp"},
    {name:"Mariposa Dorada", bg:"condition/papillon_dore_lieu.webp", cond:"condition/papillon_dore_meteo.webp", heure:"condition/papillon_dore_heure.webp"},
    {name:"Parnassius", bg:"condition/parnassien_lieu.webp", cond:"condition/parnassien_meteo.webp", heure:"condition/parnassien_heure.webp"},
    {name:"Blanca del Berro", bg:"condition/pieride_du_cresson_lieu.webp", cond:"condition/pieride_du_cresson_meteo.webp", heure:"condition/pieride_du_cresson_heure.webp"},
    {name:"Chinche Picasso", bg:"condition/punaise_picasso_lieu.webp", cond:"condition/punaise_picasso_meteo.webp", heure:"condition/punaise_picasso_heure.webp"},
    {name:"Pirocroa", bg:"condition/pyrochroa_lieu.webp", cond:"condition/pyrochroa_meteo.webp", heure:"condition/pyrochroa_heure.webp"},
    {name:"Chinche de Fuego", bg:"condition/pyrrhocoris_apterus_lieu.webp", cond:"condition/pyrrhocoris_apterus_meteo.webp", heure:"condition/pyrrhocoris_apterus_heure.webp"},
    {name:"Saltamontes del Oasis", bg:"condition/sauterelle_de_loasis_lieu.webp", cond:"condition/sauterelle_de_loasis_meteo.webp", heure:"condition/sauterelle_de_loasis_heure.webp"},
    {name:"Escarabajo Unicornio", bg:"condition/scarabee_unicorne_lieu.webp", cond:"condition/scarabee_unicorne_meteo.webp", heure:"condition/scarabee_unicorne_heure.webp"}
];

// 10. AVES
const birdList = [
    {name:"Guacamayo Azul y Amarillo", bg:"condition/ara_bleu_et_jaune_lieu.webp", cond:"condition/ara_bleu_et_jaune_meteo.webp", heure:"condition/ara_bleu_et_jaune_heure.webp"},
    {name:"Guacamayo Rojo y Verde", bg:"condition/ara_rouge_et_vert_lieu.webp", cond:"condition/ara_rouge_et_vert_meteo.webp", heure:"condition/ara_rouge_et_vert_heure.webp"},
    {name:"Guacamayo Índigo", bg:"condition/ara_indigo_lieu.webp", cond:"condition/ara_indigo_meteo.webp", heure:"condition/ara_indigo_heure.webp"},
    {name:"Lavandera Blanca", bg:"condition/bergeronnette_grise_lieu.webp", cond:"condition/bergeronnette_grise_meteo.webp", heure:"condition/bergeronnette_grise_heure.webp"},
    {name:"Camachuelo", bg:"condition/bouvreuil_lieu.webp", cond:"condition/bouvreuil_meteo.webp", heure:"condition/bouvreuil_heure.webp"},
    {name:"Camachuelo Ventrirrojo", bg:"condition/bouvreuil_a_ventre_rouge_lieu.webp", cond:"condition/bouvreuil_a_ventre_rouge_meteo.webp", heure:"condition/bouvreuil_a_ventre_rouge_heure.webp"},
    {name:"Tangara de Paraíso", bg:"condition/calliste_septicolore_lieu.webp", cond:"condition/calliste_septicolore_meteo.webp", heure:"condition/calliste_septicolore_heure.webp"},
    {name:"Malvasía Cabeciblanca", bg:"condition/canard_a_tete_blanche_lieu.webp", cond:"condition/canard_a_tete_blanche_meteo.webp", heure:"condition/canard_a_tete_blanche_heure.webp"},
    {name:"Ánade Real", bg:"condition/canard_colvert_lieu.webp", cond:"condition/canard_colvert_meteo.webp", heure:"condition/canard_colvert_heure.webp"},
    {name:"Silbón Europeo", bg:"condition/canard_siffleur_lieu.webp", cond:"condition/canard_siffleur_meteo.webp", heure:"condition/canard_siffleur_heure.webp"},
    {name:"Cardenal de Cresta Roja", bg:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_lieu.webp", cond:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_meteo.webp", heure:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_heure.webp"},
    {name:"Tilopo Jambu", bg:"condition/colombe_jambu_lieu.webp", cond:"condition/colombe_jambu_meteo.webp", heure:"condition/colombe_jambu_heure.webp"},
    {name:"Diamante Mandarín", bg:"condition/diamant_mandarin_lieu.webp", cond:"condition/diamant_mandarin_meteo.webp", heure:"condition/diamant_mandarin_heure.webp"},
    {name:"Eider Real", bg:"condition/eider_royal_lieu.webp", cond:"condition/eider_royal_meteo.webp", heure:"condition/eider_royal_heure.webp"},
    {name:"Faisán", bg:"condition/faisan_a_ventre_blanc_lieu.webp", cond:"condition/faisan_a_ventre_blanc_meteo.webp", heure:"condition/faisan_a_ventre_blanc_heure.webp"},
    {name:"Cernícalo de Patas Rojas", bg:"condition/faucon_a_pattes_rouges_lieu.webp", cond:"condition/faucon_a_pattes_rouges_meteo.webp", heure:"condition/faucon_a_pattes_rouges_heure.webp"},
    {name:"Halcón Peregrino", bg:"condition/faucon_pelerin_lieu.webp", cond:"condition/faucon_pelerin_meteo.webp", heure:"condition/faucon_pelerin_heure.webp"},
    {name:"Halcón Rojo", bg:"condition/faucon_rouge_lieu.webp", cond:"condition/faucon_rouge_meteo.webp", heure:"condition/faucon_rouge_heure.webp"},
    {name:"Flamenco Americano", bg:"condition/flamant_rose_americain_lieu.webp", cond:"condition/flamant_rose_americain_meteo.webp", heure:"condition/flamant_rose_americain_heure.webp"},
    {name:"Pinzón Vulgar", bg:"condition/fringilla_coelebs_lieu.webp", cond:"condition/fringilla_coelebs_meteo.webp", heure:"condition/fringilla_coelebs_heure.webp"},
    {name:"Papamoscas Verditer", bg:"condition/gobemouche_vertdegris_lieu.webp", cond:"condition/gobemouche_vertdegris_meteo.webp", heure:"condition/gobemouche_vertdegris_heure.webp"},
    {name:"Gaviota", bg:"condition/goeland_lieu.webp", cond:"condition/goeland_meteo.webp", heure:"condition/goeland_heure.webp"},
    {name:"Oropéndola", bg:"condition/golden_oriole_lieu.webp", cond:"condition/golden_oriole_meteo.webp", heure:"condition/golden_oriole_heure.webp"},
    {name:"Búho Real", bg:"condition/grand_duc_deurope_lieu.webp", cond:"condition/grand_duc_deurope_meteo.webp", heure:"condition/grand_duc_deurope_heure.webp"},
    {name:"Gran Flamenco", bg:"condition/grand_flamant_lieu.webp", cond:"condition/grand_flamant_meteo.webp", heure:"condition/grand_flamant_heure.webp"},
    {name:"Pico Picapinos", bg:"condition/grand_pic_lieu.webp", cond:"condition/grand_pic_meteo.webp", heure:"condition/grand_pic_heure.webp"},
    {name:"Picogordo", bg:"condition/grosbec_lieu.webp", cond:"condition/grosbec_meteo.webp", heure:"condition/grosbec_heure.webp"},
    {name:"Abejaruco Europeo", bg:"condition/guepier_deurope_lieu.webp", cond:"condition/guepier_deurope_meteo.webp", heure:"condition/guepier_deurope_heure.webp"},
    {name:"Serreta Chica", bg:"condition/harle_piette_lieu.webp", cond:"condition/harle_piette_meteo.webp", heure:"condition/harle_piette_heure.webp"},
    {name:"Búho Chico", bg:"condition/hibou_moyen_duc_lieu.webp", cond:"condition/hibou_moyen_duc_meteo.webp", heure:"condition/hibou_moyen_duc_heure.webp"},
    {name:"Pergolero Dorado", bg:"condition/jardinier_a_tete_jaune_lieu.webp", cond:"condition/jardinier_a_tete_jaune_meteo.webp", heure:"condition/jardinier_a_tete_jaune_heure.webp"},
    {name:"Pardillo", bg:"condition/linotte_a_dos_blanc_lieu.webp", cond:"condition/linotte_a_dos_blanc_meteo.webp", heure:"condition/linotte_a_dos_blanc_heure.webp"},
    {name:"Azulejo Oriental", bg:"condition/merle_bleu_de_lest_lieu.webp", cond:"condition/merle_bleu_de_lest_meteo.webp", heure:"condition/merle_bleu_de_lest_heure.webp"},
    {name:"Mito Plateado", bg:"condition/mesange_a_menton_argent_lieu.webp", cond:"condition/mesange_a_menton_argent_meteo.webp", heure:"condition/mesange_a_menton_argent_heure.webp"},
    {name:"Herrerillo Común", bg:"condition/mesange_bleue_lieu.webp", cond:"condition/mesange_bleue_meteo.webp", heure:"condition/mesange_bleue_heure.webp"},
    {name:"Mosquero Ventriamarillo", bg:"condition/moucherolle_a_ventre_jaune_lieu.webp", cond:"condition/moucherolle_a_ventre_jaune_meteo.webp", heure:"condition/moucherolle_a_ventre_jaune_heure.webp"},
    {name:"Gaviota", bg:"condition/mouette_lieu.webp", cond:"condition/mouette_meteo.webp", heure:"condition/mouette_heure.webp"},
    {name:"Bigotudo", bg:"condition/panure_a_moustache_lieu.webp", cond:"condition/panure_a_moustache_meteo.webp", heure:"condition/panure_a_moustache_heure.webp"},
    {name:"Pavo Real Blanco", bg:"condition/paon_blanc_lieu.webp", cond:"condition/paon_blanc_meteo.webp", heure:"condition/paon_blanc_heure.webp"},
    {name:"Pavo Real Azul", bg:"condition/paon_bleu_lieu.webp", cond:"condition/paon_bleu_meteo.webp", heure:"condition/paon_bleu_heure.webp"},
    {name:"Pavo Real Negro", bg:"condition/paon_noir_lieu.webp", cond:"condition/paon_noir_meteo.webp", heure:"condition/paon_noir_heure.webp"},
    {name:"Pavo Real Verde", bg:"condition/paon_vert_lieu.webp", cond:"condition/paon_vert_meteo.webp", heure:"condition/paon_vert_heure.webp"},
    {name:"Flamenco Enano", bg:"condition/petit_flamant_lieu.webp", cond:"condition/petit_flamant_meteo.webp", heure:"condition/petit_flamant_heure.webp"},
    {name:"Alcaudón Común", bg:"condition/piegrieche_a_tete_rousse_lieu.webp", cond:"condition/piegrieche_a_tete_rousse_meteo.webp", heure:"condition/piegrieche_a_tete_rousse_heure.webp"},
    {name:"Paloma Dorada", bg:"condition/pigeon_aux_fruits_dor_lieu.webp", cond:"condition/pigeon_aux_fruits_dor_meteo.webp", heure:"condition/pigeon_aux_fruits_dor_heure.webp"},
    {name:"Paloma de Ojos Amarillos", bg:"condition/pigeon_aux_yeux_jaunes_lieu.webp", cond:"condition/pigeon_aux_yeux_jaunes_meteo.webp", heure:"condition/pigeon_aux_yeux_jaunes_heure.webp"},
    {name:"Paloma Zurita", bg:"condition/pigeon_colombin_lieu.webp", cond:"condition/pigeon_colombin_meteo.webp", heure:"condition/pigeon_colombin_heure.webp"},
    {name:"Paloma Wonga", bg:"condition/pigeon_de_wonga_lieu.webp", cond:"condition/pigeon_de_wonga_meteo.webp", heure:"condition/pigeon_de_wonga_heure.webp"},
    {name:"Paloma Rosa", bg:"condition/pigeon_rose_lieu.webp", cond:"condition/pigeon_rose_meteo.webp", heure:"condition/pigeon_rose_heure.webp"},
    {name:"Pinzón", bg:"condition/pinson_lieu.webp", cond:"condition/pinson_meteo.webp", heure:"condition/pinson_heure.webp"},
    {name:"Petirrojo", bg:"condition/rougegorge_lieu.webp", cond:"condition/rougegorge_meteo.webp", heure:"condition/rougegorge_heure.webp"},
    {name:"Trepador Azul", bg:"condition/sittelle_lieu.webp", cond:"condition/sittelle_meteo.webp", heure:"condition/sittelle_heure.webp"},
    {name:"Charrán", bg:"condition/sterne_lieu.webp", cond:"condition/sterne_meteo.webp", heure:"condition/sterne_heure.webp"},
    {name:"Charrán Blanco", bg:"condition/sterne_blanche_lieu.webp", cond:"condition/sterne_blanche_meteo.webp", heure:"condition/sterne_blanche_heure.webp"},
    {name:"Tarro Canelo", bg:"condition/tadorne_casarca_lieu.webp", cond:"condition/tadorne_casarca_meteo.webp", heure:"condition/tadorne_casarca_heure.webp"},
    {name:"Tórtola de Cabeza Gris", bg:"condition/tourterelle_a_tete_grise_lieu.webp", cond:"condition/tourterelle_a_tete_grise_meteo.webp", heure:"condition/tourterelle_a_tete_grise_heure.webp"},
    {name:"Tórtola Turca", bg:"condition/tourterelle_grise_lieu.webp", cond:"condition/tourterelle_grise_meteo.webp", heure:"condition/tourterelle_grise_heure.webp"},
    {name:"Tórtola Moteada", bg:"condition/tourterelle_tigrine_lieu.webp", cond:"condition/tourterelle_tigrine_meteo.webp", heure:"condition/tourterelle_tigrine_heure.webp"},
    {name:"Chochín", bg:"condition/troglodyte_lieu.webp", cond:"condition/troglodyte_meteo.webp", heure:"condition/troglodyte_heure.webp"}
];

// 11. QUIZ (Preguntas en Español)
const QUIZ_DATA = [
    { q: "¿Quién es el guía del pueblo?", o: ["Albert Jr.", "Barnabé", "Eric"], a: 0 },
    { q: "¿Dónde se encuentra el Acantharchus pomotis?", o: ["Mar en Calma", "Lago del Bosque", "Río Aurora"], a: 0 },
    { q: "¿Qué PNJ gestiona los descubrimientos?", o: ["El Coleccionista", "Bob", "Massimo"], a: 0 },
    { q: "¿Qué clima crea el arcoíris?", o: ["Tormenta", "Niebla", "Sol tras lluvia"], a: 2 },
    { q: "¿Dónde está el Pueblo de Pescadores?", o: ["Noreste", "Suroeste", "Este"], a: 1 },
    { q: "El Actias neidhoederi es:", o: ["Matutino", "Diurno", "Nocturno"], a: 2 },
    { q: "¿Dónde vive el Capibara?", o: ["Las Ruinas", "El Trampolín", "La Playa"], a: 0 },
    { q: "¿Quién vende los animales (perros)?", o: ["Vernie", "Joan", "Andrew"], a: 1 },
    { q: "¿Dónde pescar el Pez Remo?", o: ["Ríos", "Lagos", "Océano"], a: 2 },
    { q: "¿Dónde está la zona termal?", o: ["Al Norte", "Al Sur", "Al Oeste"], a: 0 },
    { q: "El Escarabajo Unicornio vive en:", o: ["Muelle Oriental", "Campos", "Bosque"], a: 0 },
    { q: "El Guacamayo Índigo es un:", o: ["Pez", "Insecto", "Ave"], a: 2 },
    { q: "La Carpa Mariposa vive en:", o: ["Agua dulce", "Agua salada", "Lago Pradera"], a: 2 },
    { q: "¿Dónde se encuentra el PNJ Will?", o: ["Cerca del mar", "En la montaña", "En el bosque"], a: 0 },
    { q: "¿Color del botón PECES?", o: ["Verde", "Azul", "Naranja"], a: 1 },
    { q: "El Abejorro vive en:", o: ["Lagos", "Campos de Flores", "Cuevas"], a: 1 },
    { q: "La Nutria se encuentra en:", o: ["Faro", "Pueblo Pescadores", "Ruinas"], a: 1 },
    { q: "El Panda vive cerca de:", o: ["Trampolín", "Pueblo", "Muelle"], a: 0 },
    { q: "El Eperlano vive en:", o: ["Lago Pradera", "Lago Superior", "Océano"], a: 0 },
    { q: "Annie se encuentra en:", o: ["Plaza Central", "Playa", "Bosque"], a: 0 },
    { q: "La Llama vive en:", o: ["Playa Púrpura", "Montaña", "Río"], a: 0 },
    { q: "¿Nota sobre 20 para el mapa?", o: ["5", "0", "20"], a: 2 },
    { q: "El Cangrejo Noble Azul vive en:", o: ["Lago Bosque", "Océano", "Mar en Calma"], a: 0 },
    { q: "La Montaña Ballena está al:", o: ["Sur", "Norte", "Oeste"], a: 2 },
    { q: "Maptopia sirve para:", o: ["Vender ítems", "Localizar recursos", "Reemplazar el juego"], a: 1 },
    { q: "La Lavandera Blanca es un:", o: ["Ave", "Pez", "Habitante"], a: 1 },
    { q: "El Ciervo vive en:", o: ["Playa", "Bosque Robles", "Ciudad"], a: 1 },
    { q: "El Gonepteryx aspasia es un:", o: ["Fruta", "Insecto", "Pez"], a: 1 },
    { q: "El Muelle Oriental está al:", o: ["Norte", "Este", "Sur"], a: 1 },
    { q: "Bob es un:", o: ["Animal", "PNJ", "Lugar"], a: 1 }
];