// --- DADOS EM PORTUGUÊS (data-pt.js) ---

// 1. TEXTOS UI (Para multilinguagem)
const TEXTS = {
    title: "MAPTOPIA PT",
    enterBtn: "✨ ENTRAR NO MAPA ✨",
    menu: {
        pnj: "NPCs",
        animals: "ANIMAIS",
        bus: "ÔNIBUS",
        shops: "LOJAS",
        places: "LUGARES",
        fish: "PEIXES",
        bugs: "INSETOS",
        birds: "PÁSSAROS",
        resources: "RECURSOS"
    },
    chat: {
        success: "✅ Mensagem enviada com sucesso!",
        error: "❌ Erro ao enviar.",
        incomplete: "⚠️ Por favor, preencha todos os campos.",
        wait: "A enviar..."
    },
    quiz: {
        success: "✅ BRAVO!",
        error: "❌ ERRO!",
        finishTitle: "🏆 ESPECIALISTA CONFIRMADO!",
        finishText: "Conheces Heartopia como a palma da tua mão.",
        quitBtn: "SAIR DO QUIZ"
    },
    like: {
        thankyou: "OBRIGADO!",
        already: "Já votaste!"
    }
};

// 2. LISTA DE NPCs
const PNJ_DATA = [
    [-471, 501, "Bob", "pnj/bob.webp"],
    [-526, 499, "Atara", "pnj/atara.webp"],
    [-478, 493, "Colecionador", "pnj/collectioneur.webp"],
    [-469, 488, "Dorothée", "pnj/dorothée.webp"],
    [-446, 493, "Massimo", "pnj/massimo.webp"],
    [-412, 418, "Ka Ching", "pnj/ka ching.webp"],
    [-399, 591, "Andrew", "pnj/andrew.webp"],
    [-259, 522, "Eric", "pnj/eric.webp"],
    [-456, 549, "Vanya", "pnj/vanya.webp"],
    [-502, 582, "Naniwa", "pnj/naniwa.webp"],
    [-502, 519, "Sra. Joan", "pnj/mme joan.webp"],
    [-807, 419, "Will", "pnj/will.webp"],
    [-355, 809, "Patti", "pnj/patti.webp"],
    [-653, 225, "Vernie", "pnj/vernie.webp"],
    [-498, 526, "Bailey j", "pnj/bayleyj.webp"],
    [-528.3, 560.3, "Blanc", "pnj/blanc.webp"],
    [-499.8, 499.0, "Annie", "pnj/annie.webp"],
    [-532.4, 634.8, "Albert Jr.", "pnj/albert jr.webp"],
    [-734.8, 445.8, "Bill", "pnj/bill.webp"]
];

// 3. ÔNIBUS
const BUS_DATA = [
    ["Periferia Oeste",[-533,340]], ["Periferia da Vila",[-519,639]], ["Vila dos Pescadores",[-654,479]], 
    ["Campo de Flores",[-532,218]], ["Montanha Termal",[-222,512]], ["Periferia Norte",[-373,480]], 
    ["Praça Central",[-497,481]], ["Floresta",[-500,798]]
];

// 4. LOJAS
const SHOP_DATA = [
    [-472,487,"Roupas","vetement.webp"],[-474,503,"Móveis","Meuble.webp"],
    [-496.4,520.6,"Animais","chien.webp"],[-440,467,"Livraria","Librairie.webp"]
];

// 5. ANIMAIS
const ANIMAL_DATA = [
    {pos: [-691, 783], name: "Panda", img: "panda.webp", radius: 60},
    {pos: [-184, 291], name: "Capivara", img: "capybara.webp", radius: 50},
    {pos: [-533, 340], name: "Coelho", img: "lapin.webp", radius: 40},
    {pos: [-649, 185], name: "Raposa", img: "renard.webp", radius: 70},
    {pos: [-737, 512], name: "Lontra", img: "loutre.webp", radius: 40},
    {pos: [-354.3, 277.3], name: "Vison", img: "vison.webp", radius: 10},
    {pos: [-531, 805], name: "Veado", img: "cerf.webp", radius: 60},
    {pos: [-725, 208], name: "Lama", img: "lama.webp", radius: 50}
];

// 6. LUGARES
const LIEUX_DATA = [
    {pos:[-538,492], name:"Praça Central", type:"label-ville", startOn:true}, 
    {pos:[-692,506], name:"Vila dos Pescadores", type:"label-ville", startOn:true}, 
    {pos:[-438,513], name:"Rua dos Habitantes", type:"label-ville", startOn:true}, 
    {pos:[-649,185], name:"Campo de Flores", type:"label-ville", startOn:true}, 
    {pos:[-440,184], name:"Montanha da Baleia", type:"label-ville", startOn:true}, 
    {pos:[-184,291], name:"As Ruínas", type:"label-ville", startOn:true}, 
    {pos:[-223,501], name:"Montanha Termal", type:"label-ville", startOn:true}, 
    {pos:[-228,627], name:"Penhasco Rochoso", type:"label-ville", startOn:true}, 
    {pos:[-531,805], name:"Floresta de Carvalhos", type:"label-ville", startOn:true}, 
    {pos:[-494,429], name:"Rua das Artes", type:"label-ville", startOn:true}, 
    {pos:[-510,558], name:"Rua dos Jardins", type:"label-ville", startOn:true}, 
    {pos:[-736,602], name:"Cais Oriental", type:"label-ville", startOn:true}, 
    {pos:[-690,402], name:"O Cais", type:"label-ville", startOn:true}, 
    {pos:[-780,387], name:"Farol", type:"label-ville", startOn:true}, 
    {pos:[-691,783], name:"Trampolim", type:"label-ville", startOn:true}, 
    {pos:[-338,933], name:"Ilha da Floresta", type:"label-ville", startOn:true}, 
    {pos:[-587,406], name:"Periferia", type:"label-ville", startOn:true}, 
    {pos:[-725,208], name:"Praia Roxa", type:"label-ville", startOn:true}, 
    {pos:[-783,478], name:"Mar Calmo", type:"label-eau", startOn:true}, 
    {pos:[-534,92], name:"Mar da Baleia", type:"label-eau", startOn:true}, 
    {pos:[-68,497], name:"Mar Antigo", type:"label-eau", startOn:true}, 
    {pos:[-536,232], name:"Lago da Pradaria", type:"label-eau", startOn:true}, 
    {pos:[-337,319], name:"Rio Aurora", type:"label-eau", startOn:true}, 
    {pos:[-176,394], name:"Lago Vulcânico", type:"label-eau", startOn:true}, 
    {pos:[-265,537], name:"Lago Termal", type:"label-eau", startOn:true}, 
    {pos:[-344,652], name:"Rio Baixo", type:"label-eau", startOn:true}, 
    {pos:[-598,748], name:"Lago da Floresta", type:"label-eau", startOn:true}, 
    {pos:[-431,774], name:"Lago Alto da Floresta", type:"label-eau", startOn:true}, 
    {pos:[-608,481], name:"Lago da Periferia", type:"label-eau", startOn:true}, 
    {pos:[-669,368], name:"Rio Tranquilo", type:"label-eau", startOn:true}, 
    {pos:[-674,627], name:"Rio Árvores Gigantes", type:"label-eau", startOn:true}, 
    {pos:[-600,600], name:"Campo de Flores do Moinho", type:"label-ville", startOn:true}, 
    {pos:[-670,450], name:"Pontão Este", type:"label-ville", startOn:true}
];

// 7. RECURSOS
const resourcesData = {
    "Framboesa": { icon: "resource/framboise.webp", positions: [[-680.8, 330.9], [-668.5, 352.1], [-667.9, 268.5], [-648.3, 288.6], [-613.5, 317.4], [-602.8, 274.5], [-617.6, 211.6], [-571.5, 254.4], [-538.9, 208.6], [-527.8, 251.6], [-535.8, 288.3], [-503.1, 242.9], [-495, 222.4], [-453.8, 222.4], [-438.6, 246], [-395, 247.4], [-387.1, 269.5]] },
    "Mirtilo": { icon: "resource/myrtille.webp", positions: [[-642.9, 371.9], [-631.9, 368.4], [-628.5, 365.5], [-606.8, 350.3], [-602.5, 342.3], [-590.1, 334.1], [-575.6, 332.1], [-562.1, 330], [-544.9, 324.5], [-518.4, 320.3], [-515.9, 320.5], [-500.8, 321.1], [-479.3, 328.6], [-468.3, 320], [-437.3, 313.9], [-411.4, 311.4], [-400.3, 311.4], [-379.5, 304.1], [-327.4, 352], [-313.6, 339], [-328.6, 371.5], [-324.4, 389.3], [-297.9, 410.8], [-271.6, 395.4], [-319.9, 413.5], [-330.4, 421.6], [-333.4, 450], [-338.6, 468.6], [-297.4, 484.4], [-349, 489.4], [-356.5, 499.3], [-360.4, 526.4], [-355.5, 545.1], [-352.9, 565.9], [-316, 558.1], [-363.6, 578.4], [-365.3, 609], [-360.9, 628.1], [-343, 634], [-388, 655.4], [-400.9, 654.3], [-421.9, 656.4], [-444.1, 670.6], [-462.5, 654], [-476.8, 654.6], [-491.6, 656.3], [-506.4, 672.4], [-525.4, 688], [-542.6, 650], [-559.3, 644.9], [-575.6, 651], [-597.8, 643.8], [-604.8, 633.8], [-627.9, 619.4]] },
    "Maçã": { icon: "resource/pomme.webp", positions: [[-356.3, 493], [-365.4, 560.1], [-362.4, 581], [-324.6, 570.1], [-296, 610.3], [-365.6, 619.5], [-362.8, 628.5], [-393.5, 654.8], [-420.6, 653.3], [-436.1, 665.4], [-444.4, 685.1], [-436.6, 697.5], [-458.4, 744.9], [-505, 677.3], [-494.5, 657], [-459.8, 653.6], [-530.1, 677.9], [-540.1, 648.6], [-592.8, 676.6], [-606.9, 634.1], [-629.3, 623]] },
    "Grande Árvore": { icon: "resource/grand arbre.webp", positions: [[-612, 424.5], [-641.8, 369], [-351, 329.5], [-414.3, 337.1], [-396.3, 608.9], [-376.3, 624], [-616, 593.6], [-672.3, 642]] },
    "Madeira de Carvalho Escorregadia": { icon: "resource/bois de chaine glissant.webp", positions: [[-532, 787.3]] },
    "Pedra": { icon: "resource/pierre.webp", positions: [[-615.9, 316], [-641.5, 278.8], [-558.4, 257.4], [-535, 292], [-499.5, 241.1], [-466.8, 283.1], [-407.1, 244.1], [-284, 402.8], [-254.6, 367.9], [-309.4, 479.1], [-263, 466.6], [-289.1, 544.6], [-315.5, 567.9], [-298.6, 625.4], [-391.3, 726.9], [-443.6, 697], [-468.6, 733.8], [-519, 714.9], [-564.9, 732.8], [-605.1, 680.3], [-673.9, 684.1]] },
    "Fluorite": { icon: "resource/fluorite.webp", positions: [[-417.8, 313.8]] },
    "Laranja": { icon: "resource/orange.webp", positions: [[-650.1, 370.9], [-639.5, 372], [-607.3, 351.4], [-602.9, 343.5], [-588.6, 336.6], [-559.6, 329.5], [-542.1, 324.8], [-515, 319.5], [-470.5, 321], [-461.4, 271.5], [-410.8, 314], [-397.3, 310.1], [-310.9, 339.3], [-327.6, 373.9], [-324.9, 391.9], [-295.4, 411.1], [-330.4, 420.9], [-333.8, 452.9]] }
};

// 8. PEIXES
const fishList = [
    {name:"Alburno", bg:"condition/ablette_lieu.webp", cond:"condition/ablette_meteo.webp", heure:"condition/ablette_heure.webp"},
    {name:"Acantharchus pomotis", bg:"condition/acantharchus_pomotis_lieu.webp", cond:"condition/acantharchus_pomotis_meteo.webp", heure:"condition/acantharchus_pomotis_heure.webp"},
    {name:"Enguia Europeia", bg:"condition/anguille_europeenne_lieu.webp", cond:"condition/anguille_europeenne_meteo.webp", heure:"condition/anguille_europeenne_heure.webp"},
    {name:"Aphyosemion striatum", bg:"condition/aphyosemion_striatum_lieu.webp", cond:"condition/aphyosemion_striatum_meteo.webp", heure:"condition/aphyosemion_striatum_heure.webp"},
    {name:"Barbo", bg:"condition/barbeau_lieu.webp", cond:"condition/barbeau_meteo.webp", heure:"condition/barbeau_heure.webp"},
    {name:"Barbilho", bg:"condition/barbillon_lieu.webp", cond:"condition/barbillon_meteo.webp", heure:"condition/barbillon_heure.webp"},
    {name:"Tamboril", bg:"condition/baudroie_lieu.webp", cond:"condition/baudroie_meteo.webp", heure:"condition/baudroie_heure.webp"},
    {name:"Caranguejo Eremita", bg:"condition/bernard_lhermite_lieu.webp", cond:"condition/bernard_lhermite_meteo.webp", heure:"condition/bernard_lhermite_heure.webp"},
    {name:"Marachomba do rio", bg:"condition/blennie_de_riviere_lieu.webp", cond:"condition/blennie_de_riviere_meteo.webp", heure:"condition/blennie_de_riviere_heure.webp"},
    {name:"Bonito", bg:"condition/bonite_lieu.webp", cond:"condition/bonite_meteo.webp", heure:"condition/bonite_heure.webp"},
    {name:"Lúcio Manchado", bg:"condition/brochet_tachete_lieu.webp", cond:"condition/brochet_tachete_meteo.webp", heure:"condition/brochet_tachete_heure.webp"},
    {name:"Carpa Prateada", bg:"condition/carpe_argente_lieu.webp", cond:"condition/carpe_argente_meteo.webp", heure:"condition/carpe_argente_heure.webp"},
    {name:"Carpa Europeia", bg:"condition/carpe_europeenne_lieu.webp", cond:"condition/carpe_europeenne_meteo.webp", heure:"condition/carpe_europeenne_heure.webp"},
    {name:"Carpa Borboleta", bg:"condition/carpe_papillon_lieu.webp", cond:"condition/carpe_papillon_meteo.webp", heure:"condition/carpe_papillon_heure.webp"},
    {name:"Carpa Preta", bg:"condition/carpe_noire_lieu.webp", cond:"condition/carpe_noire_meteo.webp", heure:"condition/carpe_noire_heure.webp"},
    {name:"Esculpi", bg:"condition/chabot_lieu.webp", cond:"condition/chabot_meteo.webp", heure:"condition/chabot_heure.webp"},
    {name:"Quimera Prateada", bg:"condition/chimere_argentee_lieu.webp", cond:"condition/chimere_argentee_meteo.webp", heure:"condition/chimere_argentee_heure.webp"},
    {name:"Cometa", bg:"condition/comete_coussut_lieu.webp", cond:"condition/comete_coussut_meteo.webp", heure:"condition/comete_coussut_heure.webp"},
    {name:"Caranguejo de Rio", bg:"condition/crabe_de_ruisseau_lieu.webp", cond:"condition/crabe_de_ruisseau_meteo.webp", heure:"condition/crabe_de_ruisseau_heure.webp"},
    {name:"Camarão do Mar", bg:"condition/crevette_de_la_mer_lieu.webp", cond:"condition/crevette_de_la_mer_meteo.webp", heure:"condition/crevette_de_la_mer_heure.webp"},
    {name:"Camarão Verde", bg:"condition/crevette_verte_lieu.webp", cond:"condition/crevette_verte_meteo.webp", heure:"condition/crevette_verte_heure.webp"},
    {name:"Lagostim Nobre", bg:"condition/ecrevisse_noble_lieu.webp", cond:"condition/ecrevisse_noble_meteo.webp", heure:"condition/ecrevisse_noble_heure.webp"},
    {name:"Lagostim Azul", bg:"condition/ecrevisse_noble_bleue_lieu.webp", cond:"condition/ecrevisse_noble_bleue_meteo.webp", heure:"condition/ecrevisse_noble_bleue_heure.webp"},
    {name:"Eglefino", bg:"condition/eglefin_lieu.webp", cond:"condition/eglefin_meteo.webp", heure:"condition/eglefin_heure.webp"},
    {name:"Eperlano", bg:"condition/eperlan_lieu.webp", cond:"condition/eperlan_meteo.webp", heure:"condition/eperlan_heure.webp"},
    {name:"Coregono", bg:"condition/fera_lieu.webp", cond:"condition/fera_meteo.webp", heure:"condition/fera_heure.webp"},
    {name:"Achigã Grande", bg:"condition/grand_blackbasse_lieu.webp", cond:"condition/grand_blackbasse_meteo.webp", heure:"condition/grand_blackbasse_heure.webp"},
    {name:"Rã Europeia", bg:"condition/grenouille_europeenne_lieu.webp", cond:"condition/grenouille_europeenne_meteo.webp", heure:"condition/grenouille_europeenne_heure.webp"},
    {name:"Góbio", bg:"condition/gobie_lieu.webp", cond:"condition/gobie_meteo.webp", heure:"condition/gobie_heure.webp"},
    {name:"Ruivo", bg:"condition/grondin_perlon_lieu.webp", cond:"condition/grondin_perlon_meteo.webp", heure:"condition/grondin_perlon_heure.webp"},
    {name:"Cavalo-marinho", bg:"condition/hippocampe_lieu.webp", cond:"condition/hippocampe_meteo.webp", heure:"condition/hippocampe_heure.webp"},
    {name:"Salmão do Danúbio", bg:"condition/huchon_lieu.webp", cond:"condition/huchon_meteo.webp", heure:"condition/huchon_heure.webp"},
    {name:"Lagosta Europeia", bg:"condition/langouste_europeenne_lieu.webp", cond:"condition/langouste_europeenne_meteo.webp", heure:"condition/langouste_europeenne_heure.webp"},
    {name:"Cobite das flores", bg:"condition/loche_des_fleurs_lieu.webp", cond:"condition/loche_des_fleurs_meteo.webp", heure:"condition/loche_des_fleurs_heure.webp"},
    {name:"Cobite da rocha", bg:"condition/loche_des_rochers_lieu.webp", cond:"condition/loche_des_rochers_meteo.webp", heure:"condition/loche_des_rochers_heure.webp"},
    {name:"Lota do rio", bg:"condition/lotte_lieu.webp", cond:"condition/lotte_meteo.webp", heure:"condition/lotte_heure.webp"},
    {name:"Cavala", bg:"condition/maquereau_atlantique_lieu.webp", cond:"condition/maquereau_atlantique_meteo.webp", heure:"condition/maquereau_atlantique_heure.webp"},
    {name:"Mexilhão", bg:"condition/moule_lieu.webp", cond:"condition/moule_meteo.webp", heure:"condition/moule_heure.webp"},
    {name:"Truta-alpina", bg:"condition/omble_chevalier_lieu.webp", cond:"condition/omble_chevalier_meteo.webp", heure:"condition/omble_chevalier_heure.webp"},
    {name:"Corvina", bg:"condition/ombrine_lieu.webp", cond:"condition/ombrine_meteo.webp", heure:"condition/ombrine_heure.webp"},
    {name:"Goraz", bg:"condition/pagellus_bogaraveo_lieu.webp", cond:"condition/pagellus_bogaraveo_meteo.webp", heure:"condition/pagellus_bogaraveo_heure.webp"},
    {name:"Perca do Mar", bg:"condition/perche_de_mer_lieu.webp", cond:"condition/perche_de_mer_meteo.webp", heure:"condition/perche_de_mer_heure.webp"},
    {name:"Perca Ameixa", bg:"condition/perche_de_prunier_lieu.webp", cond:"condition/perche_de_prunier_meteo.webp", heure:"condition/perche_de_prunier_heure.webp"},
    {name:"Perca do Rio", bg:"condition/perche_de_riviere_lieu.webp", cond:"condition/perche_de_riviere_meteo.webp", heure:"condition/perche_de_riviere_heure.webp"},
    {name:"Polvo", bg:"condition/pieuvre_lieu.webp", cond:"condition/pieuvre_meteo.webp", heure:"condition/pieuvre_heure.webp"},
    {name:"Polvo Anão", bg:"condition/pieuvre_naine_atlantique_lieu.webp", cond:"condition/pieuvre_naine_atlantique_meteo.webp", heure:"condition/pieuvre_naine_atlantique_heure.webp"},
    {name:"Peixe-tigre", bg:"condition/poissontigre_a_ventre_rouge_lieu.webp", cond:"condition/poissontigre_a_ventre_rouge_meteo.webp", heure:"condition/poissontigre_a_ventre_rouge_heure.webp"},
    {name:"Solha", bg:"condition/plie_europeenne_lieu.webp", cond:"condition/plie_europeenne_meteo.webp", heure:"condition/plie_europeenne_heure.webp"},
    {name:"Peixe-palhaço", bg:"condition/poissonclown_lieu.webp", cond:"condition/poissonclown_meteo.webp", heure:"condition/poissonclown_heure.webp"},
    {name:"Peixe-espinho", bg:"condition/poisson_epineux_lieu.webp", cond:"condition/poisson_epineux_meteo.webp", heure:"condition/poisson_epineux_heure.webp"},
    {name:"Baiacu de Rio", bg:"condition/poissonglobe_de_riviere_lieu.webp", cond:"condition/poissonglobe_de_riviere_meteo.webp", heure:"condition/poissonglobe_de_riviere_heure.webp"},
    {name:"Peixe-dourado", bg:"condition/poisson_rouge_lieu.webp", cond:"condition/poisson_rouge_meteo.webp", heure:"condition/poisson_rouge_heure.webp"},
    {name:"Peixe-fita", bg:"condition/poisson_ruban_lieu.webp", cond:"condition/poisson_ruban_meteo.webp", heure:"condition/poisson_ruban_heure.webp"},
    {name:"Peixe de olhos vermelhos", bg:"condition/poisson_a_yeux_rouges_lieu.webp", cond:"condition/poisson_a_yeux_rouges_meteo.webp", heure:"condition/poisson_a_yeux_rouges_heure.webp"},
    {name:"Regaleco", bg:"condition/regalec_lieu.webp", cond:"condition/regalec_meteo.webp", heure:"condition/regalec_heure.webp"},
    {name:"Salmonete", bg:"condition/rouget_barbet_lieu.webp", cond:"condition/rouget_barbet_meteo.webp", heure:"condition/rouget_barbet_heure.webp"},
    {name:"Pata-roxa", bg:"condition/roussette_lieu.webp", cond:"condition/roussette_meteo.webp", heure:"condition/roussette_heure.webp"},
    {name:"Lucioperca Branca", bg:"condition/sandre_blanc_lieu.webp", cond:"condition/sandre_blanc_meteo.webp", heure:"condition/sandre_blanc_heure.webp"},
    {name:"Salmão do Atlântico", bg:"condition/saumon_atlantique_lieu.webp", cond:"condition/saumon_atlantique_meteo.webp", heure:"condition/saumon_atlantique_heure.webp"},
    {name:"Salmão Keta", bg:"condition/saumon_keta_lieu.webp", cond:"condition/saumon_keta_meteo.webp", heure:"condition/saumon_keta_heure.webp"},
    {name:"Xeréu", bg:"condition/saurel_lieu.webp", cond:"condition/saurel_meteo.webp", heure:"condition/saurel_heure.webp"},
    {name:"Sardinha", bg:"condition/sardine_lieu.webp", cond:"condition/sardine_meteo.webp", heure:"condition/sardine_heure.webp"},
    {name:"Choco", bg:"condition/seiche_europeenne_lieu.webp", cond:"condition/seiche_europeenne_meteo.webp", heure:"condition/seiche_europeenne_heure.webp"},
    {name:"Siluro Europeu", bg:"condition/silure_europeen_lieu.webp", cond:"condition/silure_europeen_meteo.webp", heure:"condition/silure_europeen_heure.webp"},
    {name:"Tenca Dourada", bg:"condition/tanche_doree_lieu.webp", cond:"condition/tanche_doree_meteo.webp", heure:"condition/tanche_doree_heure.webp"},
    {name:"Girino", bg:"condition/tetard_lieu.webp", cond:"condition/tetard_meteo.webp", heure:"condition/tetard_heure.webp"},
    {name:"Tilápia", bg:"condition/tilapia_lieu.webp", cond:"condition/tilapia_meteo.webp", heure:"condition/tilapia_heure.webp"},
    {name:"Pregado", bg:"condition/turbot_lieu.webp", cond:"condition/turbot_meteo.webp", heure:"condition/turbot_heure.webp"},
    {name:"Vairão", bg:"condition/vairon_lieu.webp", cond:"condition/vairon_meteo.webp", heure:"condition/vairon_heure.webp"},
    {name:"Zingel", bg:"condition/zingel_streber_lieu.webp", cond:"condition/zingel_streber_meteo.webp", heure:"condition/zingel_streber_heure.webp"}
];

// 9. INSETOS
const bugList = [
    {name:"Actias neidhoederi", bg:"condition/actias_neidhoederi_lieu.webp", cond:"condition/actias_neidhoederi_meteo.webp", heure:"condition/actias_neidhoederi_heure.webp"},
    {name:"Borboleta-azul", bg:"condition/azure_de_porcelaine_lieu.webp", cond:"condition/azure_de_porcelaine_meteo.webp", heure:"condition/azure_de_porcelaine_heure.webp"},
    {name:"Mamangaba", bg:"condition/bourdon_lieu.webp", cond:"condition/bourdon_meteo.webp", heure:"condition/bourdon_heure.webp"},
    {name:"Cetônia Estrela Azul", bg:"condition/cetoine_etoilee_bleue_lieu.webp", cond:"condition/cetoine_etoilee_bleue_meteo.webp", heure:"condition/cetoine_etoilee_bleue_heure.webp"},
    {name:"Cicindela Verde", bg:"condition/cicindele_verte_lieu.webp", cond:"condition/cicindele_verte_meteo.webp", heure:"condition/cicindele_verte_heure.webp"},
    {name:"Borboleta-limão", bg:"condition/citron_aspasia_lieu.webp", cond:"condition/citron_aspasia_meteo.webp", heure:"condition/citron_aspasia_heure.webp"},
    {name:"Joaninha de 7 pontos", bg:"condition/coccinelle_a_sept_points_lieu.webp", cond:"condition/coccinelle_a_sept_points_meteo.webp", heure:"condition/coccinelle_a_sept_points_heure.webp"},
    {name:"Joaninha Asiática", bg:"condition/coccinelle_asiatique_lieu.webp", cond:"condition/coccinelle_asiatique_meteo.webp", heure:"condition/coccinelle_asiatique_heure.webp"},
    {name:"Criocera do aspargo", bg:"condition/criocere_de_lasperge_lieu.webp", cond:"condition/criocere_de_lasperge_meteo.webp", heure:"condition/criocere_de_lasperge_heure.webp"},
    {name:"Gafanhoto de patas grossas", bg:"condition/criquet_aux_pattes_massives_lieu.webp", cond:"condition/criquet_aux_pattes_massives_meteo.webp", heure:"condition/criquet_aux_pattes_massives_heure.webp"},
    {name:"Libelinha Azul", bg:"condition/grand_agrion_lieu.webp", cond:"condition/grand_agrion_meteo.webp", heure:"condition/grand_agrion_heure.webp"},
    {name:"Libélula Manchada", bg:"condition/libellule_tachetee_lieu.webp", cond:"condition/libellule_tachetee_meteo.webp", heure:"condition/libellule_tachetee_heure.webp"},
    {name:"Borboleta anéis vermelhos", bg:"condition/papillon_a_anneaux_rouges_lieu.webp", cond:"condition/papillon_a_anneaux_rouges_meteo.webp", heure:"condition/papillon_a_anneaux_rouges_heure.webp"},
    {name:"Borboleta colo vermelho", bg:"condition/papillon_a_col_rouge_lieu.webp", cond:"condition/papillon_a_col_rouge_meteo.webp", heure:"condition/papillon_a_col_rouge_heure.webp"},
    {name:"Borboleta Branca", bg:"condition/papillon_blanc_lieu.webp", cond:"condition/papillon_blanc_meteo.webp", heure:"condition/papillon_blanc_heure.webp"},
    {name:"Borboleta Dourada", bg:"condition/papillon_dore_lieu.webp", cond:"condition/papillon_dore_meteo.webp", heure:"condition/papillon_dore_heure.webp"},
    {name:"Parnassius", bg:"condition/parnassien_lieu.webp", cond:"condition/parnassien_meteo.webp", heure:"condition/parnassien_heure.webp"},
    {name:"Borboleta-da-couve", bg:"condition/pieride_du_cresson_lieu.webp", cond:"condition/pieride_du_cresson_meteo.webp", heure:"condition/pieride_du_cresson_heure.webp"},
    {name:"Percevejo Picasso", bg:"condition/punaise_picasso_lieu.webp", cond:"condition/punaise_picasso_meteo.webp", heure:"condition/punaise_picasso_heure.webp"},
    {name:"Pirocroa", bg:"condition/pyrochroa_lieu.webp", cond:"condition/pyrochroa_meteo.webp", heure:"condition/pyrochroa_heure.webp"},
    {name:"Percevejo-da-tília", bg:"condition/pyrrhocoris_apterus_lieu.webp", cond:"condition/pyrrhocoris_apterus_meteo.webp", heure:"condition/pyrrhocoris_apterus_heure.webp"},
    {name:"Gafanhoto do oásis", bg:"condition/sauterelle_de_loasis_lieu.webp", cond:"condition/sauterelle_de_loasis_meteo.webp", heure:"condition/sauterelle_de_loasis_heure.webp"},
    {name:"Escaravelho Unicórnio", bg:"condition/scarabee_unicorne_lieu.webp", cond:"condition/scarabee_unicorne_meteo.webp", heure:"condition/scarabee_unicorne_heure.webp"}
];

// 10. PÁSSAROS
const birdList = [
    {name:"Arara-azul", bg:"condition/ara_bleu_et_jaune_lieu.webp", cond:"condition/ara_bleu_et_jaune_meteo.webp", heure:"condition/ara_bleu_et_jaune_heure.webp"},
    {name:"Arara-vermelha", bg:"condition/ara_rouge_et_vert_lieu.webp", cond:"condition/ara_rouge_et_vert_meteo.webp", heure:"condition/ara_rouge_et_vert_heure.webp"},
    {name:"Arara-azul-pequena", bg:"condition/ara_indigo_lieu.webp", cond:"condition/ara_indigo_meteo.webp", heure:"condition/ara_indigo_heure.webp"},
    {name:"Alvéola-branca", bg:"condition/bergeronnette_grise_lieu.webp", cond:"condition/bergeronnette_grise_meteo.webp", heure:"condition/bergeronnette_grise_heure.webp"},
    {name:"Dom-fafe", bg:"condition/bouvreuil_lieu.webp", cond:"condition/bouvreuil_meteo.webp", heure:"condition/bouvreuil_heure.webp"},
    {name:"Dom-fafe de barriga vermelha", bg:"condition/bouvreuil_a_ventre_rouge_lieu.webp", cond:"condition/bouvreuil_a_ventre_rouge_meteo.webp", heure:"condition/bouvreuil_a_ventre_rouge_heure.webp"},
    {name:"Saíra-sete-cores", bg:"condition/calliste_septicolore_lieu.webp", cond:"condition/calliste_septicolore_meteo.webp", heure:"condition/calliste_septicolore_heure.webp"},
    {name:"Pato-de-rabo-alçado", bg:"condition/canard_a_tete_blanche_lieu.webp", cond:"condition/canard_a_tete_blanche_meteo.webp", heure:"condition/canard_a_tete_blanche_heure.webp"},
    {name:"Pato-real", bg:"condition/canard_colvert_lieu.webp", cond:"condition/canard_colvert_meteo.webp", heure:"condition/canard_colvert_heure.webp"},
    {name:"Piadeira", bg:"condition/canard_siffleur_lieu.webp", cond:"condition/canard_siffleur_meteo.webp", heure:"condition/canard_siffleur_heure.webp"},
    {name:"Cardeal cinzento", bg:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_lieu.webp", cond:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_meteo.webp", heure:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_heure.webp"},
    {name:"Pombo Jambu", bg:"condition/colombe_jambu_lieu.webp", cond:"condition/colombe_jambu_meteo.webp", heure:"condition/colombe_jambu_heure.webp"},
    {name:"Diamante Mandarim", bg:"condition/diamant_mandarin_lieu.webp", cond:"condition/diamant_mandarin_meteo.webp", heure:"condition/diamant_mandarin_heure.webp"},
    {name:"Eider-real", bg:"condition/eider_royal_lieu.webp", cond:"condition/eider_royal_meteo.webp", heure:"condition/eider_royal_heure.webp"},
    {name:"Faisão Venerado", bg:"condition/faisan_a_ventre_blanc_lieu.webp", cond:"condition/faisan_a_ventre_blanc_meteo.webp", heure:"condition/faisan_a_ventre_blanc_heure.webp"},
    {name:"Falcão-de-pés-vermelhos", bg:"condition/faucon_a_pattes_rouges_lieu.webp", cond:"condition/faucon_a_pattes_rouges_meteo.webp", heure:"condition/faucon_a_pattes_rouges_heure.webp"},
    {name:"Falcão Peregrino", bg:"condition/faucon_pelerin_lieu.webp", cond:"condition/faucon_pelerin_meteo.webp", heure:"condition/faucon_pelerin_heure.webp"},
    {name:"Falcão Vermelho", bg:"condition/faucon_rouge_lieu.webp", cond:"condition/faucon_rouge_meteo.webp", heure:"condition/faucon_rouge_heure.webp"},
    {name:"Flamingo Americano", bg:"condition/flamant_rose_americain_lieu.webp", cond:"condition/flamant_rose_americain_meteo.webp", heure:"condition/flamant_rose_americain_heure.webp"},
    {name:"Tentilhão", bg:"condition/fringilla_coelebs_lieu.webp", cond:"condition/fringilla_coelebs_meteo.webp", heure:"condition/fringilla_coelebs_heure.webp"},
    {name:"Papan-moscas-verditer", bg:"condition/gobemouche_vertdegris_lieu.webp", cond:"condition/gobemouche_vertdegris_meteo.webp", heure:"condition/gobemouche_vertdegris_heure.webp"},
    {name:"Gaivota", bg:"condition/goeland_lieu.webp", cond:"condition/goeland_meteo.webp", heure:"condition/goeland_heure.webp"},
    {name:"Oriol Dourado", bg:"condition/golden_oriole_lieu.webp", cond:"condition/golden_oriole_meteo.webp", heure:"condition/golden_oriole_heure.webp"},
    {name:"Bufo-real", bg:"condition/grand_duc_deurope_lieu.webp", cond:"condition/grand_duc_deurope_meteo.webp", heure:"condition/grand_duc_deurope_heure.webp"},
    {name:"Flamingo-rosa", bg:"condition/grand_flamant_lieu.webp", cond:"condition/grand_flamant_meteo.webp", heure:"condition/grand_flamant_heure.webp"},
    {name:"Pica-pau Grande", bg:"condition/grand_pic_lieu.webp", cond:"condition/grand_pic_meteo.webp", heure:"condition/grand_pic_heure.webp"},
    {name:"Bico-grossudo", bg:"condition/grosbec_lieu.webp", cond:"condition/grosbec_meteo.webp", heure:"condition/grosbec_heure.webp"},
    {name:"Abelharuco", bg:"condition/guepier_deurope_lieu.webp", cond:"condition/guepier_deurope_meteo.webp", heure:"condition/guepier_deurope_heure.webp"},
    {name:"Merganso-pequeno", bg:"condition/harle_piette_lieu.webp", cond:"condition/harle_piette_meteo.webp", heure:"condition/harle_piette_heure.webp"},
    {name:"Bufo-pequeno", bg:"condition/hibou_moyen_duc_lieu.webp", cond:"condition/hibou_moyen_duc_meteo.webp", heure:"condition/hibou_moyen_duc_heure.webp"},
    {name:"Pássaro-jardineiro", bg:"condition/jardinier_a_tete_jaune_lieu.webp", cond:"condition/jardinier_a_tete_jaune_meteo.webp", heure:"condition/jardinier_a_tete_jaune_heure.webp"},
    {name:"Pintarroxo", bg:"condition/linotte_a_dos_blanc_lieu.webp", cond:"condition/linotte_a_dos_blanc_meteo.webp", heure:"condition/linotte_a_dos_blanc_heure.webp"},
    {name:"Pássaro Azul Oriental", bg:"condition/merle_bleu_de_lest_lieu.webp", cond:"condition/merle_bleu_de_lest_meteo.webp", heure:"condition/merle_bleu_de_lest_heure.webp"},
    {name:"Chapim de queixo prateado", bg:"condition/mesange_a_menton_argent_lieu.webp", cond:"condition/mesange_a_menton_argent_meteo.webp", heure:"condition/mesange_a_menton_argent_heure.webp"},
    {name:"Chapim-azul", bg:"condition/mesange_bleue_lieu.webp", cond:"condition/mesange_bleue_meteo.webp", heure:"condition/mesange_bleue_heure.webp"},
    {name:"Papa-moscas barriga amarela", bg:"condition/moucherolle_a_ventre_jaune_lieu.webp", cond:"condition/moucherolle_a_ventre_jaune_meteo.webp", heure:"condition/moucherolle_a_ventre_jaune_heure.webp"},
    {name:"Gaivota de cabeça preta", bg:"condition/mouette_lieu.webp", cond:"condition/mouette_meteo.webp", heure:"condition/mouette_heure.webp"},
    {name:"Chapim-de-bigodes", bg:"condition/panure_a_moustache_lieu.webp", cond:"condition/panure_a_moustache_meteo.webp", heure:"condition/panure_a_moustache_heure.webp"},
    {name:"Pavão Branco", bg:"condition/paon_blanc_lieu.webp", cond:"condition/paon_blanc_meteo.webp", heure:"condition/paon_blanc_heure.webp"},
    {name:"Pavão Azul", bg:"condition/paon_bleu_lieu.webp", cond:"condition/paon_bleu_meteo.webp", heure:"condition/paon_bleu_heure.webp"},
    {name:"Pavão Preto", bg:"condition/paon_noir_lieu.webp", cond:"condition/paon_noir_meteo.webp", heure:"condition/paon_noir_heure.webp"},
    {name:"Pavão Verde", bg:"condition/paon_vert_lieu.webp", cond:"condition/paon_vert_meteo.webp", heure:"condition/paon_vert_heure.webp"},
    {name:"Flamingo Pequeno", bg:"condition/petit_flamant_lieu.webp", cond:"condition/petit_flamant_meteo.webp", heure:"condition/petit_flamant_heure.webp"},
    {name:"Picanço-barreteiro", bg:"condition/piegrieche_a_tete_rousse_lieu.webp", cond:"condition/piegrieche_a_tete_rousse_meteo.webp", heure:"condition/piegrieche_a_tete_rousse_heure.webp"},
    {name:"Pombo da fruta dourado", bg:"condition/pigeon_aux_fruits_dor_lieu.webp", cond:"condition/pigeon_aux_fruits_dor_meteo.webp", heure:"condition/pigeon_aux_fruits_dor_heure.webp"},
    {name:"Pombo de olhos amarelos", bg:"condition/pigeon_aux_yeux_jaunes_lieu.webp", cond:"condition/pigeon_aux_yeux_jaunes_meteo.webp", heure:"condition/pigeon_aux_yeux_jaunes_heure.webp"},
    {name:"Pombo-bravo", bg:"condition/pigeon_colombin_lieu.webp", cond:"condition/pigeon_colombin_meteo.webp", heure:"condition/pigeon_colombin_heure.webp"},
    {name:"Pombo Wonga", bg:"condition/pigeon_de_wonga_lieu.webp", cond:"condition/pigeon_de_wonga_meteo.webp", heure:"condition/pigeon_de_wonga_heure.webp"},
    {name:"Pombo Rosa", bg:"condition/pigeon_rose_lieu.webp", cond:"condition/pigeon_rose_meteo.webp", heure:"condition/pigeon_rose_heure.webp"},
    {name:"Tentilhão", bg:"condition/pinson_lieu.webp", cond:"condition/pinson_meteo.webp", heure:"condition/pinson_heure.webp"},
    {name:"Pisco-de-peito-ruivo", bg:"condition/rougegorge_lieu.webp", cond:"condition/rougegorge_meteo.webp", heure:"condition/rougegorge_heure.webp"},
    {name:"Trepadeira-azul", bg:"condition/sittelle_lieu.webp", cond:"condition/sittelle_meteo.webp", heure:"condition/sittelle_heure.webp"},
    {name:"Andorinha-do-mar", bg:"condition/sterne_lieu.webp", cond:"condition/sterne_meteo.webp", heure:"condition/sterne_heure.webp"},
    {name:"Andorinha-do-mar Branca", bg:"condition/sterne_blanche_lieu.webp", cond:"condition/sterne_blanche_meteo.webp", heure:"condition/sterne_blanche_heure.webp"},
    {name:"Tadorna", bg:"condition/tadorne_casarca_lieu.webp", cond:"condition/tadorne_casarca_meteo.webp", heure:"condition/tadorne_casarca_heure.webp"},
    {name:"Rola-de-cabeça-cinza", bg:"condition/tourterelle_a_tete_grise_lieu.webp", cond:"condition/tourterelle_a_tete_grise_meteo.webp", heure:"condition/tourterelle_a_tete_grise_heure.webp"},
    {name:"Rola-turca", bg:"condition/tourterelle_grise_lieu.webp", cond:"condition/tourterelle_grise_meteo.webp", heure:"condition/tourterelle_grise_heure.webp"},
    {name:"Rola-tigre", bg:"condition/tourterelle_tigrine_lieu.webp", cond:"condition/tourterelle_tigrine_meteo.webp", heure:"condition/tourterelle_tigrine_heure.webp"},
    {name:"Carriça", bg:"condition/troglodyte_lieu.webp", cond:"condition/troglodyte_meteo.webp", heure:"condition/troglodyte_heure.webp"}
];

// 11. QUIZ (Renomeado QUIZ_DATA para consistência com app.js)
const QUIZ_DATA = [
    { q: "Quem é o guia da vila?", o: ["Albert Jr.", "Barnabé", "Eric"], a: 0 },
    { q: "Onde se encontra o Acantharchus pomotis?", o: ["Mar Calmo", "Lago da Floresta", "Rio Aurora"], a: 0 },
    { q: "Qual NPC gere as coleções?", o: ["O Colecionador", "Bob", "Massimo"], a: 0 },
    { q: "Que clima cria o arco-íris?", o: ["Tempestade", "Nevoeiro", "Sol após chuva"], a: 2 },
    { q: "Onde fica a Vila dos Pescadores?", o: ["Nordeste", "Sudoeste", "Leste"], a: 1 },
    { q: "O Actias neidhoederi é:", o: ["Matinal", "Diurno", "Noturno"], a: 2 },
    { q: "Onde vive a Capivara?", o: ["Ruínas", "Trampolim", "Praia"], a: 0 },
    { q: "Quem vende os animais (cães)?", o: ["Vernie", "Joan", "Andrew"], a: 1 },
    { q: "Onde pescar o Regaleco?", o: ["Rios", "Lagos", "Oceano"], a: 2 },
    { q: "Onde fica a zona termal?", o: ["A Norte", "A Sul", "A Oeste"], a: 0 },
    { q: "O Escaravelho Unicórnio vive:", o: ["Cais Oriental", "Campos", "Floresta"], a: 0 },
    { q: "A Arara-azul-pequena é um:", o: ["Peixe", "Inseto", "Pássaro"], a: 2 },
    { q: "A Carpa Borboleta vive em:", o: ["Água doce", "Água salgada", "Lago Pradaria"], a: 2 },
    { q: "Onde está o NPC Will?", o: ["Perto do mar", "Na montanha", "Na floresta"], a: 0 },
    { q: "Cor do botão PEIXES?", o: ["Verde", "Azul", "Laranja"], a: 1 },
    { q: "A Mamangaba vive em:", o: ["Lagos", "Campos de flores", "Grutas"], a: 1 },
    { q: "A Lontra encontra-se no:", o: ["Farol", "Vila dos Pescadores", "Ruínas"], a: 1 },
    { q: "O Panda vive perto do:", o: ["Trampolim", "Vila", "Cais"], a: 0 },
    { q: "O Eperlano vive no:", o: ["Lago Pradaria", "Lago Alto", "Oceano"], a: 0 },
    { q: "A Annie encontra-se na:", o: ["Praça Central", "Praia", "Floresta"], a: 0 },
    { q: "O Lama vive na:", o: ["Praia Roxa", "Montanha", "Rio"], a: 0 },
    { q: "Nota de 0 a 20 para o mapa?", o: ["5", "0", "20"], a: 2 },
    { q: "O Lagostim Azul vive no:", o: ["Lago Floresta", "Oceano", "Mar Calmo"], a: 0 },
    { q: "A Montanha da Baleia fica a:", o: ["Sul", "Norte", "Oeste"], a: 2 },
    { q: "O Maptopia serve para:", o: ["Vender itens", "Localizar recursos", "Substituir o jogo"], a: 1 },
    { q: "A Alvéola-branca é um:", o: ["Pássaro", "Peixe", "Habitante"], a: 1 },
    { q: "O Veado vive na:", o: ["Praia", "Floresta de Carvalhos", "Cidade"], a: 1 },
    { q: "A Borboleta-limão é um:", o: ["Fruto", "Inseto", "Peixe"], a: 1 },
    { q: "O Cais Oriental fica a:", o: ["Norte", "Leste", "Sul"], a: 1 },
    { q: "Bob é um:", o: ["Animal", "NPC", "Lugar"], a: 1 }
];