// --- DATA INDONESIA (data-in.js) ---

// 1. TEKS ANTARMUKA (UI)
const TEXTS = {
    title: "MAPTOPIA IN",
    enterBtn: "✨ MASUK KE PETA ✨",
    menu: {
        pnj: "NPC",
        animals: "HEWAN",
        bus: "BUS",
        shops: "TOKO",
        places: "LOKASI",
        fish: "IKAN",
        bugs: "SERANGGA",
        birds: "BURUNG",
        resources: "SUMBER DAYA"
    },
    chat: {
        success: "✅ Pesan berhasil dikirim!",
        error: "❌ Gagal mengirim.",
        incomplete: "⚠️ Harap isi semua kolom.",
        wait: "Mengirim..."
    },
    quiz: {
        success: "✅ BENAR!",
        error: "❌ SALAH!",
        finishTitle: "🏆 PAKAR TERKONFIRMASI!",
        finishText: "Kamu tahu Heartopia luar dalam.",
        quitBtn: "KELUAR KUIS"
    },
    like: {
        thankyou: "TERIMA KASIH!",
        already: "Kamu sudah memilih!"
    }
};

// 2. DAFTAR NPC
const PNJ_DATA = [
    [-471, 501, "Bob", "pnj/bob.webp"],
    [-526, 499, "Atara", "pnj/atara.webp"],
    [-478, 493, "Kolektor", "pnj/collectioneur.webp"],
    [-469, 488, "Dorothée", "pnj/dorothée.webp"],
    [-446, 493, "Massimo", "pnj/massimo.webp"],
    [-412, 418, "Ka Ching", "pnj/ka ching.webp"],
    [-399, 591, "Andrew", "pnj/andrew.webp"],
    [-259, 522, "Eric", "pnj/eric.webp"],
    [-456, 549, "Vanya", "pnj/vanya.webp"],
    [-502, 582, "Naniwa", "pnj/naniwa.webp"],
    [-502, 519, "Joan", "pnj/mme joan.webp"],
    [-807, 419, "Will", "pnj/will.webp"],
    [-355, 809, "Patti", "pnj/patti.webp"],
    [-653, 225, "Vernie", "pnj/vernie.webp"],
    [-498, 526, "Bayley", "pnj/bayleyj.webp"],
    [-528.3, 560.3, "Blanc", "pnj/blanc.webp"],
    [-499.8, 499.0, "Annie", "pnj/annie.webp"],
    [-532.4, 634.8, "Albert Jr.", "pnj/albert jr.webp"],
    [-734.8, 445.8, "Bill", "pnj/bill.webp"]
];

// 3. PEMBERHENTIAN BUS
const BUS_DATA = [
    ["Pinggiran Barat",[-533,340]], ["Pinggiran Desa",[-519,639]], ["Desa Nelayan",[-654,479]], 
    ["Ladang Bunga",[-532,218]], ["Gunung Termal",[-222,512]], ["Pinggiran Utara",[-373,480]], 
    ["Alun-alun Pusat",[-497,481]], ["Hutan",[-500,798]]
];

// 4. TOKO
const SHOP_DATA = [
    [-472,487,"Pakaian","vetement.webp"],[-474,503,"Perabotan","Meuble.webp"],
    [-496.4,520.6,"Hewan Peliharaan","chien.webp"],[-440,467,"Toko Buku","Librairie.webp"]
];

// 5. HEWAN
const ANIMAL_DATA = [
    {pos: [-691, 783], name: "Panda", img: "panda.webp", radius: 60},
    {pos: [-184, 291], name: "Kapibara", img: "capybara.webp", radius: 50},
    {pos: [-533, 340], name: "Kelinci", img: "lapin.webp", radius: 40},
    {pos: [-649, 185], name: "Rubah", img: "renard.webp", radius: 70},
    {pos: [-737, 512], name: "Berang-berang", img: "loutre.webp", radius: 40},
    {pos: [-354.3, 277.3], name: "Mink", img: "vison.webp", radius: 10},
    {pos: [-531, 805], name: "Rusa", img: "cerf.webp", radius: 60},
    {pos: [-725, 208], name: "Llama", img: "lama.webp", radius: 50}
];

// 6. LOKASI
const LIEUX_DATA = [
    {pos:[-538,492], name:"Alun-alun Pusat", type:"label-ville", startOn:true}, 
    {pos:[-692,506], name:"Desa Nelayan", type:"label-ville", startOn:true}, 
    {pos:[-438,513], name:"Jalan Penduduk", type:"label-ville", startOn:true}, 
    {pos:[-649,185], name:"Ladang Bunga", type:"label-ville", startOn:true}, 
    {pos:[-440,184], name:"Gunung Paus", type:"label-ville", startOn:true}, 
    {pos:[-184,291], name:"Reruntuhan", type:"label-ville", startOn:true}, 
    {pos:[-223,501], name:"Gunung Termal", type:"label-ville", startOn:true}, 
    {pos:[-228,627], name:"Tebing Batu", type:"label-ville", startOn:true}, 
    {pos:[-531,805], name:"Hutan Oak", type:"label-ville", startOn:true}, 
    {pos:[-494,429], name:"Jalan Seni", type:"label-ville", startOn:true}, 
    {pos:[-510,558], name:"Jalan Taman", type:"label-ville", startOn:true}, 
    {pos:[-736,602], name:"Dermaga Timur", type:"label-ville", startOn:true}, 
    {pos:[-690,402], name:"Dermaga", type:"label-ville", startOn:true}, 
    {pos:[-780,387], name:"Mercusuar", type:"label-ville", startOn:true}, 
    {pos:[-691,783], name:"Papan Loncat", type:"label-ville", startOn:true}, 
    {pos:[-338,933], name:"Pulau Hutan", type:"label-ville", startOn:true}, 
    {pos:[-587,406], name:"Pinggiran Kota", type:"label-ville", startOn:true}, 
    {pos:[-725,208], name:"Pantai Ungu", type:"label-ville", startOn:true}, 
    {pos:[-783,478], name:"Laut Tenang", type:"label-eau", startOn:true}, 
    {pos:[-534,92], name:"Laut Paus", type:"label-eau", startOn:true}, 
    {pos:[-68,497], name:"Laut Kuno", type:"label-eau", startOn:true}, 
    {pos:[-536,232], name:"Danau Padang Rumput", type:"label-eau", startOn:true}, 
    {pos:[-337,319], name:"Sungai Aurora", type:"label-eau", startOn:true}, 
    {pos:[-176,394], name:"Danau Vulkanik", type:"label-eau", startOn:true}, 
    {pos:[-265,537], name:"Danau Air Panas", type:"label-eau", startOn:true}, 
    {pos:[-344,652], name:"Sungai Dangkal", type:"label-eau", startOn:true}, 
    {pos:[-598,748], name:"Danau Hutan", type:"label-eau", startOn:true}, 
    {pos:[-431,774], name:"Danau Atas", type:"label-eau", startOn:true}, 
    {pos:[-608,481], name:"Danau Pinggiran", type:"label-eau", startOn:true}, 
    {pos:[-669,368], name:"Sungai Tenang", type:"label-eau", startOn:true}, 
    {pos:[-674,627], name:"Sungai Pohon Raksasa", type:"label-eau", startOn:true}, 
    {pos:[-600,600], name:"Kincir Angin Bunga", type:"label-ville", startOn:true}, 
    {pos:[-670,450], name:"Ponton Timur", type:"label-ville", startOn:true}
];

// 7. SUMBER DAYA
const resourcesData = {
    "Raspberry": { icon: "resource/framboise.webp", positions: [[-680.8, 330.9], [-668.5, 352.1], [-667.9, 268.5], [-648.3, 288.6], [-613.5, 317.4], [-602.8, 274.5], [-617.6, 211.6], [-571.5, 254.4], [-538.9, 208.6], [-527.8, 251.6], [-535.8, 288.3], [-503.1, 242.9], [-495, 222.4], [-453.8, 222.4], [-438.6, 246], [-395, 247.4], [-387.1, 269.5]] },
    "Blueberry": { icon: "resource/myrtille.webp", positions: [[-642.9, 371.9], [-631.9, 368.4], [-628.5, 365.5], [-606.8, 350.3], [-602.5, 342.3], [-590.1, 334.1], [-575.6, 332.1], [-562.1, 330], [-544.9, 324.5], [-518.4, 320.3], [-515.9, 320.5], [-500.8, 321.1], [-479.3, 328.6], [-468.3, 320], [-437.3, 313.9], [-411.4, 311.4], [-400.3, 311.4], [-379.5, 304.1], [-327.4, 352], [-313.6, 339], [-328.6, 371.5], [-324.4, 389.3], [-297.9, 410.8], [-271.6, 395.4], [-319.9, 413.5], [-330.4, 421.6], [-333.4, 450], [-338.6, 468.6], [-297.4, 484.4], [-349, 489.4], [-356.5, 499.3], [-360.4, 526.4], [-355.5, 545.1], [-352.9, 565.9], [-316, 558.1], [-363.6, 578.4], [-365.3, 609], [-360.9, 628.1], [-343, 634], [-388, 655.4], [-400.9, 654.3], [-421.9, 656.4], [-444.1, 670.6], [-462.5, 654], [-476.8, 654.6], [-491.6, 656.3], [-506.4, 672.4], [-525.4, 688], [-542.6, 650], [-559.3, 644.9], [-575.6, 651], [-597.8, 643.8], [-604.8, 633.8], [-627.9, 619.4]] },
    "Apel": { icon: "resource/pomme.webp", positions: [[-356.3, 493], [-365.4, 560.1], [-362.4, 581], [-324.6, 570.1], [-296, 610.3], [-365.6, 619.5], [-362.8, 628.5], [-393.5, 654.8], [-420.6, 653.3], [-436.1, 665.4], [-444.4, 685.1], [-436.6, 697.5], [-458.4, 744.9], [-505, 677.3], [-494.5, 657], [-459.8, 653.6], [-530.1, 677.9], [-540.1, 648.6], [-592.8, 676.6], [-606.9, 634.1], [-629.3, 623]] },
    "Pohon Besar": { icon: "resource/grand arbre.webp", positions: [[-612, 424.5], [-641.8, 369], [-351, 329.5], [-414.3, 337.1], [-396.3, 608.9], [-376.3, 624], [-616, 593.6], [-672.3, 642]] },
    "Kayu Oak Licin": { icon: "resource/bois de chaine glissant.webp", positions: [[-532, 787.3]] },
    "Batu": { icon: "resource/pierre.webp", positions: [[-615.9, 316], [-641.5, 278.8], [-558.4, 257.4], [-535, 292], [-499.5, 241.1], [-466.8, 283.1], [-407.1, 244.1], [-284, 402.8], [-254.6, 367.9], [-309.4, 479.1], [-263, 466.6], [-289.1, 544.6], [-315.5, 567.9], [-298.6, 625.4], [-391.3, 726.9], [-443.6, 697], [-468.6, 733.8], [-519, 714.9], [-564.9, 732.8], [-605.1, 680.3], [-673.9, 684.1]] },
    "Fluorit": { icon: "resource/fluorite.webp", positions: [[-417.8, 313.8]] },
    "Jeruk": { icon: "resource/orange.webp", positions: [[-650.1, 370.9], [-639.5, 372], [-607.3, 351.4], [-602.9, 343.5], [-588.6, 336.6], [-559.6, 329.5], [-542.1, 324.8], [-515, 319.5], [-470.5, 321], [-461.4, 271.5], [-410.8, 314], [-397.3, 310.1], [-310.9, 339.3], [-327.6, 373.9], [-324.9, 391.9], [-295.4, 411.1], [-330.4, 420.9], [-333.8, 452.9]] }
};

// 8. IKAN
const fishList = [
    {name:"Bleak", bg:"condition/ablette_lieu.webp", cond:"condition/ablette_meteo.webp", heure:"condition/ablette_heure.webp"},
    {name:"Acantharchus pomotis", bg:"condition/acantharchus_pomotis_lieu.webp", cond:"condition/acantharchus_pomotis_meteo.webp", heure:"condition/acantharchus_pomotis_heure.webp"},
    {name:"Belut Eropa", bg:"condition/anguille_europeenne_lieu.webp", cond:"condition/anguille_europeenne_meteo.webp", heure:"condition/anguille_europeenne_heure.webp"},
    {name:"Aphyosemion striatum", bg:"condition/aphyosemion_striatum_lieu.webp", cond:"condition/aphyosemion_striatum_meteo.webp", heure:"condition/aphyosemion_striatum_heure.webp"},
    {name:"Barbel", bg:"condition/barbeau_lieu.webp", cond:"condition/barbeau_meteo.webp", heure:"condition/barbeau_heure.webp"},
    {name:"Barbel Kecil", bg:"condition/barbillon_lieu.webp", cond:"condition/barbillon_meteo.webp", heure:"condition/barbillon_heure.webp"},
    {name:"Anglerfish", bg:"condition/baudroie_lieu.webp", cond:"condition/baudroie_meteo.webp", heure:"condition/baudroie_heure.webp"},
    {name:"Kelomang", bg:"condition/bernard_lhermite_lieu.webp", cond:"condition/bernard_lhermite_meteo.webp", heure:"condition/bernard_lhermite_heure.webp"},
    {name:"Blenny Sungai", bg:"condition/blennie_de_riviere_lieu.webp", cond:"condition/blennie_de_riviere_meteo.webp", heure:"condition/blennie_de_riviere_heure.webp"},
    {name:"Bonito", bg:"condition/bonite_lieu.webp", cond:"condition/bonite_meteo.webp", heure:"condition/bonite_heure.webp"},
    {name:"Pike Berbintik", bg:"condition/brochet_tachete_lieu.webp", cond:"condition/brochet_tachete_meteo.webp", heure:"condition/brochet_tachete_heure.webp"},
    {name:"Ikan Mas Perak", bg:"condition/carpe_argente_lieu.webp", cond:"condition/carpe_argente_meteo.webp", heure:"condition/carpe_argente_heure.webp"},
    {name:"Ikan Mas Eropa", bg:"condition/carpe_europeenne_lieu.webp", cond:"condition/carpe_europeenne_meteo.webp", heure:"condition/carpe_europeenne_heure.webp"},
    {name:"Ikan Mas Kupu-kupu", bg:"condition/carpe_papillon_lieu.webp", cond:"condition/carpe_papillon_meteo.webp", heure:"condition/carpe_papillon_heure.webp"},
    {name:"Ikan Mas Hitam", bg:"condition/carpe_noire_lieu.webp", cond:"condition/carpe_noire_meteo.webp", heure:"condition/carpe_noire_heure.webp"},
    {name:"Sculpin", bg:"condition/chabot_lieu.webp", cond:"condition/chabot_meteo.webp", heure:"condition/chabot_heure.webp"},
    {name:"Chimaera Perak", bg:"condition/chimere_argentee_lieu.webp", cond:"condition/chimere_argentee_meteo.webp", heure:"condition/chimere_argentee_heure.webp"},
    {name:"Ikan Mas Komet", bg:"condition/comete_coussut_lieu.webp", cond:"condition/comete_coussut_meteo.webp", heure:"condition/comete_coussut_heure.webp"},
    {name:"Kepiting Sungai", bg:"condition/crabe_de_ruisseau_lieu.webp", cond:"condition/crabe_de_ruisseau_meteo.webp", heure:"condition/crabe_de_ruisseau_heure.webp"},
    {name:"Udang Laut", bg:"condition/crevette_de_la_mer_lieu.webp", cond:"condition/crevette_de_la_mer_meteo.webp", heure:"condition/crevette_de_la_mer_heure.webp"},
    {name:"Udang Hijau", bg:"condition/crevette_verte_lieu.webp", cond:"condition/crevette_verte_meteo.webp", heure:"condition/crevette_verte_heure.webp"},
    {name:"Lobster Mulia", bg:"condition/ecrevisse_noble_lieu.webp", cond:"condition/ecrevisse_noble_meteo.webp", heure:"condition/ecrevisse_noble_heure.webp"},
    {name:"Lobster Mulia Biru", bg:"condition/ecrevisse_noble_bleue_lieu.webp", cond:"condition/ecrevisse_noble_bleue_meteo.webp", heure:"condition/ecrevisse_noble_bleue_heure.webp"},
    {name:"Haddock", bg:"condition/eglefin_lieu.webp", cond:"condition/eglefin_meteo.webp", heure:"condition/eglefin_heure.webp"},
    {name:"Smelt", bg:"condition/eperlan_lieu.webp", cond:"condition/eperlan_meteo.webp", heure:"condition/eperlan_heure.webp"},
    {name:"Whitefish", bg:"condition/fera_lieu.webp", cond:"condition/fera_meteo.webp", heure:"condition/fera_heure.webp"},
    {name:"Bass Hitam Besar", bg:"condition/grand_blackbasse_lieu.webp", cond:"condition/grand_blackbasse_meteo.webp", heure:"condition/grand_blackbasse_heure.webp"},
    {name:"Katak Eropa", bg:"condition/grenouille_europeenne_lieu.webp", cond:"condition/grenouille_europeenne_meteo.webp", heure:"condition/grenouille_europeenne_heure.webp"},
    {name:"Goby", bg:"condition/gobie_lieu.webp", cond:"condition/gobie_meteo.webp", heure:"condition/gobie_heure.webp"},
    {name:"Tub Gurnard", bg:"condition/grondin_perlon_lieu.webp", cond:"condition/grondin_perlon_meteo.webp", heure:"condition/grondin_perlon_heure.webp"},
    {name:"Kuda Laut", bg:"condition/hippocampe_lieu.webp", cond:"condition/hippocampe_meteo.webp", heure:"condition/hippocampe_heure.webp"},
    {name:"Huchen", bg:"condition/huchon_lieu.webp", cond:"condition/huchon_meteo.webp", heure:"condition/huchon_heure.webp"},
    {name:"Lobster Duri Eropa", bg:"condition/langouste_europeenne_lieu.webp", cond:"condition/langouste_europeenne_meteo.webp", heure:"condition/langouste_europeenne_heure.webp"},
    {name:"Flower Loach", bg:"condition/loche_des_fleurs_lieu.webp", cond:"condition/loche_des_fleurs_meteo.webp", heure:"condition/loche_des_fleurs_heure.webp"},
    {name:"Stone Loach", bg:"condition/loche_des_rochers_lieu.webp", cond:"condition/loche_des_rochers_meteo.webp", heure:"condition/loche_des_rochers_heure.webp"},
    {name:"Monkfish", bg:"condition/lotte_lieu.webp", cond:"condition/lotte_meteo.webp", heure:"condition/lotte_heure.webp"},
    {name:"Makarel Atlantik", bg:"condition/maquereau_atlantique_lieu.webp", cond:"condition/maquereau_atlantique_meteo.webp", heure:"condition/maquereau_atlantique_heure.webp"},
    {name:"Kerang", bg:"condition/moule_lieu.webp", cond:"condition/moule_meteo.webp", heure:"condition/moule_heure.webp"},
    {name:"Arctic Char", bg:"condition/omble_chevalier_lieu.webp", cond:"condition/omble_chevalier_meteo.webp", heure:"condition/omble_chevalier_heure.webp"},
    {name:"Croaker", bg:"condition/ombrine_lieu.webp", cond:"condition/ombrine_meteo.webp", heure:"condition/ombrine_heure.webp"},
    {name:"Blackspot Seabream", bg:"condition/pagellus_bogaraveo_lieu.webp", cond:"condition/pagellus_bogaraveo_meteo.webp", heure:"condition/pagellus_bogaraveo_heure.webp"},
    {name:"Sea Perch", bg:"condition/perche_de_mer_lieu.webp", cond:"condition/perche_de_mer_meteo.webp", heure:"condition/perche_de_mer_heure.webp"},
    {name:"Plum Perch", bg:"condition/perche_de_prunier_lieu.webp", cond:"condition/perche_de_prunier_meteo.webp", heure:"condition/perche_de_prunier_heure.webp"},
    {name:"River Perch", bg:"condition/perche_de_riviere_lieu.webp", cond:"condition/perche_de_riviere_meteo.webp", heure:"condition/perche_de_riviere_heure.webp"},
    {name:"Gurita", bg:"condition/pieuvre_lieu.webp", cond:"condition/pieuvre_meteo.webp", heure:"condition/pieuvre_heure.webp"},
    {name:"Gurita Kerdil", bg:"condition/pieuvre_naine_atlantique_lieu.webp", cond:"condition/pieuvre_naine_atlantique_meteo.webp", heure:"condition/pieuvre_naine_atlantique_heure.webp"},
    {name:"Tigerfish", bg:"condition/poissontigre_a_ventre_rouge_lieu.webp", cond:"condition/poissontigre_a_ventre_rouge_meteo.webp", heure:"condition/poissontigre_a_ventre_rouge_heure.webp"},
    {name:"European Plaice", bg:"condition/plie_europeenne_lieu.webp", cond:"condition/plie_europeenne_meteo.webp", heure:"condition/plie_europeenne_heure.webp"},
    {name:"Ikan Badut", bg:"condition/poissonclown_lieu.webp", cond:"condition/poissonclown_meteo.webp", heure:"condition/poissonclown_heure.webp"},
    {name:"Stickleback", bg:"condition/poisson_epineux_lieu.webp", cond:"condition/poisson_epineux_meteo.webp", heure:"condition/poisson_epineux_heure.webp"},
    {name:"River Pufferfish", bg:"condition/poissonglobe_de_riviere_lieu.webp", cond:"condition/poissonglobe_de_riviere_meteo.webp", heure:"condition/poissonglobe_de_riviere_heure.webp"},
    {name:"Ikan Mas", bg:"condition/poisson_rouge_lieu.webp", cond:"condition/poisson_rouge_meteo.webp", heure:"condition/poisson_rouge_heure.webp"},
    {name:"Ribbonfish", bg:"condition/poisson_ruban_lieu.webp", cond:"condition/poisson_ruban_meteo.webp", heure:"condition/poisson_ruban_heure.webp"},
    {name:"Red-Eyed Fish", bg:"condition/poisson_a_yeux_rouges_lieu.webp", cond:"condition/poisson_a_yeux_rouges_meteo.webp", heure:"condition/poisson_a_yeux_rouges_heure.webp"},
    {name:"Oarfish", bg:"condition/regalec_lieu.webp", cond:"condition/regalec_meteo.webp", heure:"condition/regalec_heure.webp"},
    {name:"Red Mullet", bg:"condition/rouget_barbet_lieu.webp", cond:"condition/rouget_barbet_meteo.webp", heure:"condition/rouget_barbet_heure.webp"},
    {name:"Dogfish", bg:"condition/roussette_lieu.webp", cond:"condition/roussette_meteo.webp", heure:"condition/roussette_heure.webp"},
    {name:"White Zander", bg:"condition/sandre_blanc_lieu.webp", cond:"condition/sandre_blanc_meteo.webp", heure:"condition/sandre_blanc_heure.webp"},
    {name:"Salmon Atlantik", bg:"condition/saumon_atlantique_lieu.webp", cond:"condition/saumon_atlantique_meteo.webp", heure:"condition/saumon_atlantique_heure.webp"},
    {name:"Chum Salmon", bg:"condition/saumon_keta_lieu.webp", cond:"condition/saumon_keta_meteo.webp", heure:"condition/saumon_keta_heure.webp"},
    {name:"Horse Mackerel", bg:"condition/saurel_lieu.webp", cond:"condition/saurel_meteo.webp", heure:"condition/saurel_heure.webp"},
    {name:"Sarden", bg:"condition/sardine_lieu.webp", cond:"condition/sardine_meteo.webp", heure:"condition/sardine_heure.webp"},
    {name:"Sotong", bg:"condition/seiche_europeenne_lieu.webp", cond:"condition/seiche_europeenne_meteo.webp", heure:"condition/seiche_europeenne_heure.webp"},
    {name:"Wels Catfish", bg:"condition/silure_europeen_lieu.webp", cond:"condition/silure_europeen_meteo.webp", heure:"condition/silure_europeen_heure.webp"},
    {name:"Golden Tench", bg:"condition/tanche_doree_lieu.webp", cond:"condition/tanche_doree_meteo.webp", heure:"condition/tanche_doree_heure.webp"},
    {name:"Berudu", bg:"condition/tetard_lieu.webp", cond:"condition/tetard_meteo.webp", heure:"condition/tetard_heure.webp"},
    {name:"Tilapia", bg:"condition/tilapia_lieu.webp", cond:"condition/tilapia_meteo.webp", heure:"condition/tilapia_heure.webp"},
    {name:"Turbot", bg:"condition/turbot_lieu.webp", cond:"condition/turbot_meteo.webp", heure:"condition/turbot_heure.webp"},
    {name:"Minnow", bg:"condition/vairon_lieu.webp", cond:"condition/vairon_meteo.webp", heure:"condition/vairon_heure.webp"},
    {name:"Zingel Streber", bg:"condition/zingel_streber_lieu.webp", cond:"condition/zingel_streber_meteo.webp", heure:"condition/zingel_streber_heure.webp"}
];

// 9. SERANGGA
const bugList = [
    {name:"Actias neidhoederi", bg:"condition/actias_neidhoederi_lieu.webp", cond:"condition/actias_neidhoederi_meteo.webp", heure:"condition/actias_neidhoederi_heure.webp"},
    {name:"Holly Blue", bg:"condition/azure_de_porcelaine_lieu.webp", cond:"condition/azure_de_porcelaine_meteo.webp", heure:"condition/azure_de_porcelaine_heure.webp"},
    {name:"Bumblebee", bg:"condition/bourdon_lieu.webp", cond:"condition/bourdon_meteo.webp", heure:"condition/bourdon_heure.webp"},
    {name:"Kumbang Bunga Bintang Biru", bg:"condition/cetoine_etoilee_bleue_lieu.webp", cond:"condition/cetoine_etoilee_bleue_meteo.webp", heure:"condition/cetoine_etoilee_bleue_heure.webp"},
    {name:"Kumbang Harimau Hijau", bg:"condition/cicindele_verte_lieu.webp", cond:"condition/cicindele_verte_meteo.webp", heure:"condition/cicindele_verte_heure.webp"},
    {name:"Gonepteryx aspasia", bg:"condition/citron_aspasia_lieu.webp", cond:"condition/citron_aspasia_meteo.webp", heure:"condition/citron_aspasia_heure.webp"},
    {name:"Kepik 7 Titik", bg:"condition/coccinelle_a_sept_points_lieu.webp", cond:"condition/coccinelle_a_sept_points_meteo.webp", heure:"condition/coccinelle_a_sept_points_heure.webp"},
    {name:"Kepik Asia", bg:"condition/coccinelle_asiatique_lieu.webp", cond:"condition/coccinelle_asiatique_meteo.webp", heure:"condition/coccinelle_asiatique_heure.webp"},
    {name:"Kumbang Asparagus", bg:"condition/criocere_de_lasperge_lieu.webp", cond:"condition/criocere_de_lasperge_meteo.webp", heure:"condition/criocere_de_lasperge_heure.webp"},
    {name:"Belalang Kaki Kuat", bg:"condition/criquet_aux_pattes_massives_lieu.webp", cond:"condition/criquet_aux_pattes_massives_meteo.webp", heure:"condition/criquet_aux_pattes_massives_heure.webp"},
    {name:"Capung Jarum Besar", bg:"condition/grand_agrion_lieu.webp", cond:"condition/grand_agrion_meteo.webp", heure:"condition/grand_agrion_heure.webp"},
    {name:"Capung Tutul", bg:"condition/libellule_tachetee_lieu.webp", cond:"condition/libellule_tachetee_meteo.webp", heure:"condition/libellule_tachetee_heure.webp"},
    {name:"Kupu-kupu Cincin Merah", bg:"condition/papillon_a_anneaux_rouges_lieu.webp", cond:"condition/papillon_a_anneaux_rouges_meteo.webp", heure:"condition/papillon_a_anneaux_rouges_heure.webp"},
    {name:"Kupu-kupu Leher Merah", bg:"condition/papillon_a_col_rouge_lieu.webp", cond:"condition/papillon_a_col_rouge_meteo.webp", heure:"condition/papillon_a_col_rouge_heure.webp"},
    {name:"Kupu-kupu Putih", bg:"condition/papillon_blanc_lieu.webp", cond:"condition/papillon_blanc_meteo.webp", heure:"condition/papillon_blanc_heure.webp"},
    {name:"Kupu-kupu Emas", bg:"condition/papillon_dore_lieu.webp", cond:"condition/papillon_dore_meteo.webp", heure:"condition/papillon_dore_heure.webp"},
    {name:"Parnassian", bg:"condition/parnassien_lieu.webp", cond:"condition/parnassien_meteo.webp", heure:"condition/parnassien_heure.webp"},
    {name:"Kupu-kupu Kubis", bg:"condition/pieride_du_cresson_lieu.webp", cond:"condition/pieride_du_cresson_meteo.webp", heure:"condition/pieride_du_cresson_heure.webp"},
    {name:"Kepik Picasso", bg:"condition/punaise_picasso_lieu.webp", cond:"condition/punaise_picasso_meteo.webp", heure:"condition/punaise_picasso_heure.webp"},
    {name:"Pyrochroa", bg:"condition/pyrochroa_lieu.webp", cond:"condition/pyrochroa_meteo.webp", heure:"condition/pyrochroa_heure.webp"},
    {name:"Firebug", bg:"condition/pyrrhocoris_apterus_lieu.webp", cond:"condition/pyrrhocoris_apterus_meteo.webp", heure:"condition/pyrrhocoris_apterus_heure.webp"},
    {name:"Belalang Oasis", bg:"condition/sauterelle_de_loasis_lieu.webp", cond:"condition/sauterelle_de_loasis_meteo.webp", heure:"condition/sauterelle_de_loasis_heure.webp"},
    {name:"Kumbang Unicorn", bg:"condition/scarabee_unicorne_lieu.webp", cond:"condition/scarabee_unicorne_meteo.webp", heure:"condition/scarabee_unicorne_heure.webp"}
];

// 10. BURUNG
const birdList = [
    {name:"Macaw Biru-Kuning", bg:"condition/ara_bleu_et_jaune_lieu.webp", cond:"condition/ara_bleu_et_jaune_meteo.webp", heure:"condition/ara_bleu_et_jaune_heure.webp"},
    {name:"Macaw Merah-Hijau", bg:"condition/ara_rouge_et_vert_lieu.webp", cond:"condition/ara_rouge_et_vert_meteo.webp", heure:"condition/ara_rouge_et_vert_heure.webp"},
    {name:"Macaw Indigo", bg:"condition/ara_indigo_lieu.webp", cond:"condition/ara_indigo_meteo.webp", heure:"condition/ara_indigo_heure.webp"},
    {name:"White Wagtail", bg:"condition/bergeronnette_grise_lieu.webp", cond:"condition/bergeronnette_grise_meteo.webp", heure:"condition/bergeronnette_grise_heure.webp"},
    {name:"Bullfinch", bg:"condition/bouvreuil_lieu.webp", cond:"condition/bouvreuil_meteo.webp", heure:"condition/bouvreuil_heure.webp"},
    {name:"Red-bellied Bullfinch", bg:"condition/bouvreuil_a_ventre_rouge_lieu.webp", cond:"condition/bouvreuil_a_ventre_rouge_meteo.webp", heure:"condition/bouvreuil_a_ventre_rouge_heure.webp"},
    {name:"Green-headed Tanager", bg:"condition/calliste_septicolore_lieu.webp", cond:"condition/calliste_septicolore_meteo.webp", heure:"condition/calliste_septicolore_heure.webp"},
    {name:"White-headed Duck", bg:"condition/canard_a_tete_blanche_lieu.webp", cond:"condition/canard_a_tete_blanche_meteo.webp", heure:"condition/canard_a_tete_blanche_heure.webp"},
    {name:"Mallard", bg:"condition/canard_colvert_lieu.webp", cond:"condition/canard_colvert_meteo.webp", heure:"condition/canard_colvert_heure.webp"},
    {name:"Wigeon", bg:"condition/canard_siffleur_lieu.webp", cond:"condition/canard_siffleur_meteo.webp", heure:"condition/canard_siffleur_heure.webp"},
    {name:"Red-crested Cardinal", bg:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_lieu.webp", cond:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_meteo.webp", heure:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_heure.webp"},
    {name:"Jambu Fruit Dove", bg:"condition/colombe_jambu_lieu.webp", cond:"condition/colombe_jambu_meteo.webp", heure:"condition/colombe_jambu_heure.webp"},
    {name:"Zebra Finch", bg:"condition/diamant_mandarin_lieu.webp", cond:"condition/diamant_mandarin_meteo.webp", heure:"condition/diamant_mandarin_heure.webp"},
    {name:"King Eider", bg:"condition/eider_royal_lieu.webp", cond:"condition/eider_royal_meteo.webp", heure:"condition/eider_royal_heure.webp"},
    {name:"White-bellied Pheasant", bg:"condition/faisan_a_ventre_blanc_lieu.webp", cond:"condition/faisan_a_ventre_blanc_meteo.webp", heure:"condition/faisan_a_ventre_blanc_heure.webp"},
    {name:"Red-footed Falcon", bg:"condition/faucon_a_pattes_rouges_lieu.webp", cond:"condition/faucon_a_pattes_rouges_meteo.webp", heure:"condition/faucon_a_pattes_rouges_heure.webp"},
    {name:"Peregrine Falcon", bg:"condition/faucon_pelerin_lieu.webp", cond:"condition/faucon_pelerin_meteo.webp", heure:"condition/faucon_pelerin_heure.webp"},
    {name:"Red Falcon", bg:"condition/faucon_rouge_lieu.webp", cond:"condition/faucon_rouge_meteo.webp", heure:"condition/faucon_rouge_heure.webp"},
    {name:"American Flamingo", bg:"condition/flamant_rose_americain_lieu.webp", cond:"condition/flamant_rose_americain_meteo.webp", heure:"condition/flamant_rose_americain_heure.webp"},
    {name:"Chaffinch", bg:"condition/fringilla_coelebs_lieu.webp", cond:"condition/fringilla_coelebs_meteo.webp", heure:"condition/fringilla_coelebs_heure.webp"},
    {name:"Verditer Flycatcher", bg:"condition/gobemouche_vertdegris_lieu.webp", cond:"condition/gobemouche_vertdegris_meteo.webp", heure:"condition/gobemouche_vertdegris_heure.webp"},
    {name:"Gull", bg:"condition/goeland_lieu.webp", cond:"condition/goeland_meteo.webp", heure:"condition/goeland_heure.webp"},
    {name:"Golden Oriole", bg:"condition/golden_oriole_lieu.webp", cond:"condition/golden_oriole_meteo.webp", heure:"condition/golden_oriole_heure.webp"},
    {name:"Eurasian Eagle-Owl", bg:"condition/grand_duc_deurope_lieu.webp", cond:"condition/grand_duc_deurope_meteo.webp", heure:"condition/grand_duc_deurope_heure.webp"},
    {name:"Greater Flamingo", bg:"condition/grand_flamant_lieu.webp", cond:"condition/grand_flamant_meteo.webp", heure:"condition/grand_flamant_heure.webp"},
    {name:"Great Spotted Woodpecker", bg:"condition/grand_pic_lieu.webp", cond:"condition/grand_pic_meteo.webp", heure:"condition/grand_pic_heure.webp"},
    {name:"Hawfinch", bg:"condition/grosbec_lieu.webp", cond:"condition/grosbec_meteo.webp", heure:"condition/grosbec_heure.webp"},
    {name:"European Bee-eater", bg:"condition/guepier_deurope_lieu.webp", cond:"condition/guepier_deurope_meteo.webp", heure:"condition/guepier_deurope_heure.webp"},
    {name:"Smew", bg:"condition/harle_piette_lieu.webp", cond:"condition/harle_piette_meteo.webp", heure:"condition/harle_piette_heure.webp"},
    {name:"Long-eared Owl", bg:"condition/hibou_moyen_duc_lieu.webp", cond:"condition/hibou_moyen_duc_meteo.webp", heure:"condition/hibou_moyen_duc_heure.webp"},
    {name:"Golden Bowerbird", bg:"condition/jardinier_a_tete_jaune_lieu.webp", cond:"condition/jardinier_a_tete_jaune_meteo.webp", heure:"condition/jardinier_a_tete_jaune_heure.webp"},
    {name:"White-backed Linnet", bg:"condition/linotte_a_dos_blanc_lieu.webp", cond:"condition/linotte_a_dos_blanc_meteo.webp", heure:"condition/linotte_a_dos_blanc_heure.webp"},
    {name:"Eastern Bluebird", bg:"condition/merle_bleu_de_lest_lieu.webp", cond:"condition/merle_bleu_de_lest_meteo.webp", heure:"condition/merle_bleu_de_lest_heure.webp"},
    {name:"Silver-throated Tit", bg:"condition/mesange_a_menton_argent_lieu.webp", cond:"condition/mesange_a_menton_argent_meteo.webp", heure:"condition/mesange_a_menton_argent_heure.webp"},
    {name:"Blue Tit", bg:"condition/mesange_bleue_lieu.webp", cond:"condition/mesange_bleue_meteo.webp", heure:"condition/mesange_bleue_heure.webp"},
    {name:"Yellow-bellied Flycatcher", bg:"condition/moucherolle_a_ventre_jaune_lieu.webp", cond:"condition/moucherolle_a_ventre_jaune_meteo.webp", heure:"condition/moucherolle_a_ventre_jaune_heure.webp"},
    {name:"Seagull", bg:"condition/mouette_lieu.webp", cond:"condition/mouette_meteo.webp", heure:"condition/mouette_heure.webp"},
    {name:"Bearded Reedling", bg:"condition/panure_a_moustache_lieu.webp", cond:"condition/panure_a_moustache_meteo.webp", heure:"condition/panure_a_moustache_heure.webp"},
    {name:"White Peacock", bg:"condition/paon_blanc_lieu.webp", cond:"condition/paon_blanc_meteo.webp", heure:"condition/paon_blanc_heure.webp"},
    {name:"Blue Peacock", bg:"condition/paon_bleu_lieu.webp", cond:"condition/paon_bleu_meteo.webp", heure:"condition/paon_bleu_heure.webp"},
    {name:"Black Peacock", bg:"condition/paon_noir_lieu.webp", cond:"condition/paon_noir_meteo.webp", heure:"condition/paon_noir_heure.webp"},
    {name:"Green Peacock", bg:"condition/paon_vert_lieu.webp", cond:"condition/paon_vert_meteo.webp", heure:"condition/paon_vert_heure.webp"},
    {name:"Lesser Flamingo", bg:"condition/petit_flamant_lieu.webp", cond:"condition/petit_flamant_meteo.webp", heure:"condition/petit_flamant_heure.webp"},
    {name:"Woodchat Shrike", bg:"condition/piegrieche_a_tete_rousse_lieu.webp", cond:"condition/piegrieche_a_tete_rousse_meteo.webp", heure:"condition/piegrieche_a_tete_rousse_heure.webp"},
    {name:"Golden Fruit Dove", bg:"condition/pigeon_aux_fruits_dor_lieu.webp", cond:"condition/pigeon_aux_fruits_dor_meteo.webp", heure:"condition/pigeon_aux_fruits_dor_heure.webp"},
    {name:"Yellow-eyed Pigeon", bg:"condition/pigeon_aux_yeux_jaunes_lieu.webp", cond:"condition/pigeon_aux_yeux_jaunes_meteo.webp", heure:"condition/pigeon_aux_yeux_jaunes_heure.webp"},
    {name:"Stock Dove", bg:"condition/pigeon_colombin_lieu.webp", cond:"condition/pigeon_colombin_meteo.webp", heure:"condition/pigeon_colombin_heure.webp"},
    {name:"Wonga Pigeon", bg:"condition/pigeon_de_wonga_lieu.webp", cond:"condition/pigeon_de_wonga_meteo.webp", heure:"condition/pigeon_de_wonga_heure.webp"},
    {name:"Pink Pigeon", bg:"condition/pigeon_rose_lieu.webp", cond:"condition/pigeon_rose_meteo.webp", heure:"condition/pigeon_rose_heure.webp"},
    {name:"Finch", bg:"condition/pinson_lieu.webp", cond:"condition/pinson_meteo.webp", heure:"condition/pinson_heure.webp"},
    {name:"Robin", bg:"condition/rougegorge_lieu.webp", cond:"condition/rougegorge_meteo.webp", heure:"condition/rougegorge_heure.webp"},
    {name:"Nuthatch", bg:"condition/sittelle_lieu.webp", cond:"condition/sittelle_meteo.webp", heure:"condition/sittelle_heure.webp"},
    {name:"Tern", bg:"condition/sterne_lieu.webp", cond:"condition/sterne_meteo.webp", heure:"condition/sterne_heure.webp"},
    {name:"White Tern", bg:"condition/sterne_blanche_lieu.webp", cond:"condition/sterne_blanche_meteo.webp", heure:"condition/sterne_blanche_heure.webp"},
    {name:"Ruddy Shelduck", bg:"condition/tadorne_casarca_lieu.webp", cond:"condition/tadorne_casarca_meteo.webp", heure:"condition/tadorne_casarca_heure.webp"},
    {name:"Grey-headed Dove", bg:"condition/tourterelle_a_tete_grise_lieu.webp", cond:"condition/tourterelle_a_tete_grise_meteo.webp", heure:"condition/tourterelle_a_tete_grise_heure.webp"},
    {name:"Collared Dove", bg:"condition/tourterelle_grise_lieu.webp", cond:"condition/tourterelle_grise_meteo.webp", heure:"condition/tourterelle_grise_heure.webp"},
    {name:"Spotted Dove", bg:"condition/tourterelle_tigrine_lieu.webp", cond:"condition/tourterelle_tigrine_meteo.webp", heure:"condition/tourterelle_tigrine_heure.webp"},
    {name:"Wren", bg:"condition/troglodyte_lieu.webp", cond:"condition/troglodyte_meteo.webp", heure:"condition/troglodyte_heure.webp"}
];

// 11. KUIS
const QUIZ_DATA = [
    { q: "Siapa pemandu desa?", o: ["Albert Jr.", "Barnabé", "Eric"], a: 0 },
    { q: "Di mana Acantharchus pomotis dapat ditemukan?", o: ["Laut Tenang", "Danau Hutan", "Sungai Aurora"], a: 0 },
    { q: "NPC mana yang mengelola penemuan?", o: ["Kolektor", "Bob", "Massimo"], a: 0 },
    { q: "Cuaca apa yang menciptakan pelangi?", o: ["Badai", "Kabut", "Matahari setelah hujan"], a: 2 },
    { q: "Di mana lokasi Desa Nelayan?", o: ["Timur Laut", "Barat Daya", "Timur"], a: 1 },
    { q: "Actias neidhoederi muncul saat:", o: ["Pagi", "Siang", "Malam"], a: 2 },
    { q: "Di mana Kapibara tinggal?", o: ["Reruntuhan", "Papan Loncat", "Pantai"], a: 0 },
    { q: "Siapa yang menjual hewan (anjing)?", o: ["Vernie", "Joan", "Andrew"], a: 1 },
    { q: "Di mana menangkap Oarfish?", o: ["Sungai", "Danau", "Laut"], a: 2 },
    { q: "Di mana area termal?", o: ["Utara", "Selatan", "Barat"], a: 0 },
    { q: "Kumbang Unicorn tinggal di:", o: ["Dermaga Timur", "Ladang", "Hutan"], a: 0 },
    { q: "Macaw Indigo adalah:", o: ["Ikan", "Serangga", "Burung"], a: 2 },
    { q: "Ikan Mas Kupu-kupu hidup di:", o: ["Air tawar", "Air asin", "Danau Padang Rumput"], a: 2 },
    { q: "Di mana NPC Will berada?", o: ["Dekat laut", "Di gunung", "Di hutan"], a: 0 },
    { q: "Warna tombol IKAN?", o: ["Hijau", "Biru", "Oranye"], a: 1 },
    { q: "Kumbang Bumblebee tinggal di:", o: ["Danau", "Ladang Bunga", "Gua"], a: 1 },
    { q: "Berang-berang ditemukan di:", o: ["Mercusuar", "Desa Nelayan", "Reruntuhan"], a: 1 },
    { q: "Panda tinggal di dekat:", o: ["Papan Loncat", "Desa", "Dermaga"], a: 0 },
    { q: "Smelt hidup di:", o: ["Danau Padang Rumput", "Danau Atas", "Laut"], a: 0 },
    { q: "Annie berada di:", o: ["Alun-alun Pusat", "Pantai", "Hutan"], a: 0 },
    { q: "Llama tinggal di:", o: ["Pantai Ungu", "Gunung", "Sungai"], a: 0 },
    { q: "Nilai peta dari 20?", o: ["5", "0", "20"], a: 2 },
    { q: "Lobster Mulia Biru hidup di:", o: ["Danau Hutan", "Laut", "Laut Tenang"], a: 0 },
    { q: "Gunung Paus berada di sebelah:", o: ["Selatan", "Utara", "Barat"], a: 2 },
    { q: "Maptopia digunakan untuk:", o: ["Menjual item", "Mencari sumber daya", "Menggantikan game"], a: 1 },
    { q: "White Wagtail adalah:", o: ["Burung", "Ikan", "Penduduk"], a: 1 },
    { q: "Rusa hidup di:", o: ["Pantai", "Hutan Oak", "Kota"], a: 1 },
    { q: "Gonepteryx aspasia adalah:", o: ["Buah", "Serangga", "Ikan"], a: 1 },
    { q: "Dermaga Timur berada di:", o: ["Utara", "Timur", "Selatan"], a: 1 },
    { q: "Bob adalah:", o: ["Hewan", "NPC", "Tempat"], a: 1 }
];